### ISSUE TITLE
play button and export/import for debugger

### ISSUE THREAD

**Issue by ksmth** [christianalfoni/cerebral#10]
I think it'd be kind of neat to have some kind of `play` button in the debugger. I haven't had a look at the source yet, but for this to work, I think it'd need the time stamping of all state changes so they could be replayed at the same distance from each other.

Also, it'd be neat if you could export/import a session for later replay.

**Comment by christianalfoni** [comment]
Absolutely! This is one of the concepts that Cerebral can support :-)

**Comment by christianalfoni** [comment]
I am reimplementing a service that I have worked on, www.jsfridge.com. The functionality there will now use Cerebral instead, allowing for "isolated" recording and playback of signals. So it will not be like the recording / remember of the debugger, which is resetting the complete app. This will rather be a possibility to record signals and play them back, respecting the timing between them. It will also be up to the application to be set in the correct state before running the signals... at least my initial thought :-)

**Comment by christianalfoni** [comment]
Okay, this is in place in first version. Need to document a bit, but take a look at this video for an introduction: https://www.youtube.com/watch?v=c5lZbJ95tqc
