### ISSUE TITLE
Using cerebral debugger runs signals and alters state

### ISSUE THREAD

**Issue by itaylor** [christianalfoni/cerebral#100]
I have a simple demo cerebral app using immutable-store and react that I'm playing around with.  It has one signal that has one action that sets one key in the model to false.   It has a setTimeout that calls the signal after 5 seconds.

When I use this without the debugger installed, it works as I'd expect.  After 5 seconds, the signal triggers the action, which updates the model, and the react component that is subscribed to be notified of that model changes re-renders with the correct new state.

When I use this with the debugger installed, my signal is called immediately after the initial render.  If I set a breakpoint in the action, it is hit ~5 times before the setTimeout triggers.

Is this expected behavior?  Why would the debugger be doing this?

**Comment by jeroenverfallie** [comment]
The debuggers will by default record all signals on the session. It keeps those stored and replays them on a hard refresh. 

This makes debugging certain down-the-line actions easy because you don't need to click/type through your UI over and over. 

If you uncheck "keep signals" it won't do this.

**Comment by itaylor** [comment]
Ok, cool, thanks.  Maybe that checkbox should be renamed to "Replay Signals"?  The name "keep signals" made me think that it would be the "Preserve logs" checkbox in the normal Chrome console.

**Comment by christianalfoni** [comment]
@itaylor Great input! Will change it on next version :-)

**Comment by christianalfoni** [comment]
though... hm... replay only indicates the refresh. it also keeps the signals as they are triggered to let you time travel debug... hm hm... let me think about it :-) But yes, this is a confusion and should change

**Comment by itaylor** [comment]
Yeah, maybe the right thing is to separate the replaying on reload functionality from the storing of signals on the current page.   They're both useful features, but I don't know that you necessarily always want them both active at the same time.

**Comment by christianalfoni** [comment]
@itaylor Yeah, that is even better, lets separate them, thanks. Getting too used to it, good to have some fresh eyes :-)
