### ISSUE TITLE
Placeholder signals cause runBranch to throw exception

### ISSUE THREAD

**Issue by garth** [christianalfoni/cerebral#104]
This is a minor issue, but it may cause confusion.

When adding new signals, sometimes I create a signal with no actions as a placeholder for the implementation.

```js
controller.signal('somethingHappend'
  // implementation will go here later
);
```

When a signal has no actions `runBranch` throws an exception.

**Comment by christianalfoni** [comment]
Just closing this, as it will be covered in other issue
