### ISSUE TITLE
Suggestion on computed functions

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral#115]
I have been working on an idea where you can compute state more easily. And I think I might have something here. If this makes sense it will probably be implemented into Cerebral and can work with any immutable state store.

To make the implementation less intrusive a "computed tree" will be added to the model. I think this makes things more readable, it is easy for debugger to handle and it is an addition... rather than putting it inside Cerebral.

### Benefits

1. You can define a computation with a normal function
2. You do not have to define its dependencies, it will track it based on values grabbed using the `get` function passed in
3. It will only rerun when its state store value or any of its previously grabbed state has changed
4. The great benefit here is that it will track the state you actually extract. An example of this is 500 messages and you display 10 of them. It will only rerun if any of these 10 actually change, not whenever any of the other messages changes, which is typical behaviour. It will of course also rerun if you change the value the computed function points to

### How to use

Set initial data:

```js
const model = Model({
  messages: {},
  displayedMessages: []
});

// You create a second tree where you point to paths where
// you want to compute the values
model.compute({
  displayedMessages: function (ids, get) {
    return ids.map((id) => get(['messages', id]));
  }
});
```
Set data using action:
```js
function myAction (input, state) {
  state.set('displayedMessages', ['123']);
  state.push('displayedMessages', '456');
}
```

Use computed value in component:
```js
export default Component({
  messages: ['displayedMessages']
}, (props) => (
  <div>
    {props.messages.length}
  </div>
));
```
### How it works

1. When Cerebral initializes it will have two trees. A state store tree and a compute tree
2. When an action or component tries to `get` values from a path that matches a computed path the function will run
3. The value stored in the state tree will be grabbed and passed to the function
4. The currently cached `get` paths and values are reset, allowing the computed `get` function to build up the new cache
5. When the computed `get` function is used it will cache the returned values and their paths
6. The returned value from the computed function is also cached
7. When an action or components uses the `get` method again the computed function will do a shallow check on the passed value and all cached path/values. If nothing has changed it will return the cached computed value, if not it will run it again

So basically instead of listening to top level changes on cursors, we do shallow checks on the state extracted when the computed function was last run.

### A practical example

```js
const model = Model({
  messages: {},
  lists: {
    displayedMessages: []
  }
});

model.compute({
  lists: {
    displayedMessages: function (ids, get) {
      return ids.map((id) => get(['messages', id]));
    }
  }
});
```

A component grabs the state, which will run the function. **Note** that it has to point specifically to the value or it will not compute. The reason is that Cerebral would have to deep clone, insert computed values and freeze again if this was not the case. It is just too heavy of a computation I think.

```js
export default Component({
  messages: ['lists', 'displayedMessages']
}, (props) => (
  <div>
    {props.messages.length}
  </div>
));
```
Since the result of the function is an empty array, this DIV will display `0`.

A signal runs this action:

```js
function addMessage (input, state) {
  state.set(['messages', input.message.id], input.message);
  state.push(['lists', 'messagesDisplayed'], input.message.id); // ["123"]
}
```

The signal tells the UI to update and the same component will run Cerebrals `get` method to grab *messagesDisplayed*. Since the value inside the state store is now changed to `['123']` the computed function will reset the current path/value cache and run again:

```js
export default Component({
  messages: ['lists', 'displayedMessages']
}, (props) => (
  <div>
    {props.messages.length}
  </div>
));
```
Now it displays **1** and you would have access to the data of the message.

Now you change the message using:

```js
function updateMessage (input, state) {
  state.merge(['messages', input.id], input.update);
}
```

The signal again tells UI to update and the component will again try to use Cerebral `get` method to update its state. Now the array `['123']` inside the state store is the same, but the path/value used with the computed functions `get` function previously is not the same anymore. So it will run again and give the new result.

### Get, export and import
When using Cerebrals `get` method it will only return computed values when pointing directly to the state. If not it will return the actual value in the state tree. Since there are no special values in the state tree an `export` does the same thing. When you use *import* Cerebral already handles this as a deep merge.

### Dynamic
```js
function myAction (input, state) {
  state.set(['foo', 'bar'], []);
  state.compute(['foo', 'bar'], function () {});
}
```
To remove a computed node you would just remove the node, `state.unset(['foo', 'bar']);`

### Caveat
Now there is just one caveat. You have to point directly to the state value to run the computation. 

### Summary
Okay, so using shallow checking on immutable values and this smart computed  `get` function we get super performance, a very simple syntax and it works with any state store... also immutable-js. 

Just want to give a big thanks to @Yomguithereal for doing an excellent work with Baobab. Everything I have ever done related to state stores are inspired by his work.

Please give me your feedback on this. If you see scenarios it would not work. Or if you just do not like it :-)

**Comment by Guria** [comment]
It is amazing. Want it already implemented :)

**Comment by saulshanabrook** [comment]
Haven't finished yet, but looks promising. Why does it use the null value? Why not just some other constant? Like a [symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol)?

**Comment by Guria** [comment]
@saulshanabrook it must be json serializable to store in tree.

**Comment by Yomguithereal** [comment]
How would you handle conditions in the function @christianalfoni? In some cases, the get function would be called with one path, and in other cases with another path. How can you keep track of dependencies likewise?

**Comment by Yomguithereal** [comment]
I see the advantages about the shallow checking part and the more relevant computed nodes updates but as I understand it you will need to rerun the computing functions on every read of the node no?

**Comment by Guria** [comment]
@Yomguithereal the same input argument would lead to the same deps call everytime. I think it described well in `A practical example` chapter

**Comment by Guria** [comment]
@Yomguithereal if value of computed node is not changed -> check recorded deps -> if nothing changed return cached value

**Comment by christianalfoni** [comment]
@Yomguithereal I missed on important point in the description there. Whenever the computed functions runs its deps is reset. So you build up deps for each run of the function. On every `get` call to the computed value it will check if its current value or any deps on last run has changed. If not changes, return cached value or clear deps and run again to build up a new cached path/deps... if that makes sense :-)

**Comment by christianalfoni** [comment]
Updated documentation with that now

**Comment by Yomguithereal** [comment]
One thing which I find misleading is the double semantics you give to the setters. Using `set` on a computed node actually has a totally different meaning than on a static one. Plus, how do you change a dynamic node? Do you have to reset an upper node (sorry if there is a solution above and I missed it).

**Comment by Yomguithereal** [comment]
On a slightly different matter, I discovered quite painfully that computed node must rewrite the tree and not be calculated and solved on read because of immutability/persistence. For obvious performance reasons and particularly if you want the history of the state and time travel to remain possible and not find yourself going back to past things not computed and that cannot be computed anymore because you forgot to stash some older things.

**Comment by christianalfoni** [comment]
The initial `null` value is not ideal here, but you treat this value as a normal state value. You can do any mutations you want on it. This value will be passed to the computed function when it runs. And it only runs when you try to grab the state value where it is defined.

I did not write anything about dynamically handling this :-) But you would use `set` and `unset` to do this. `set` checks if the value is a function and puts a `null` value in the state store and registers the computed node. `unset` removes the current value from state store and unregisters the computed node. I will add this to documentation.

Hm, my theory here is that you treat the state store as a normal state store. The only thing inside the state store is the values where functions are converted to `null` values. You can change these `null` values just like you change any other values. So typically you would have a state change when you fire up the app that sets this `null` to an array of ids.

Whenever a `get` is done to this path it will do a shallow check on value passed and any existing path/value on previous run. So it basically works like React components. The important thing is that whenever you `get` a computed value it will run based on the current state of the tree, which it should. 

The big benefit here though is when you have lots of data updates. The computed node will still only check changes on what it actually grabbed on previous run. So you can do lots of updates to your 500 messages, but only changes to the 10 on the computed node will actually make the computed node rerun itself. Does not make much difference normally, but yeah, feels right :-)

So yeah, I am not saying I am right about this :-) I just think it is a really interesting approach to rely on shallow checks on the data the computed node actually needs. Not a general path. Also the concept of wrapping it around an existing value in the state store I really like, though this `null` thingy is a bit confusing.

**Comment by christianalfoni** [comment]
Hm, an idea here would be to define a state tree and a computed tree. So:

```js
const model = Model({
  messages: {},
  currentMessages: [],
  admin: {
    users: {},
    currentUser: null
  }
});

model.compute({
  currentMessages: function (ids, get) {
    return ids.map((id) => get(['messages', id]);
  },
  admin: {
    currentUser: function (id, get) {
      return id ? get(['admin', 'users', id]) : null;
    }
  }
});

```

It is a bit fragile in the sense that you have to match the structure, but again, it would be easy to throw errors on incompatability. It is also easier to understand, as you specifically wrap the state value with a function.

Just a thought :-)

**Comment by christianalfoni** [comment]
Okay, changing documentation to this suggestion as it a lot less intrusive to current Cerebral code. And would be a nice experiment I think.

**Comment by christianalfoni** [comment]
Okay, have implemented an experiment on this, creating new issue

**Comment by Yomguithereal** [comment]
Can you reference the issue :)?

**Comment by christianalfoni** [comment]
hehe, sorry, #118

**Comment by Yomguithereal** [comment]
Thanks.
