### ISSUE TITLE
toJS vs extractState

### ISSUE THREAD

**Issue by RJ** [christianalfoni/cerebral#12]
This works:

`myCerebral.get("foo").toJS()`

... and i expected this to work, but it doesn't:

`myCerebral.toJS()`

so i'm using this, to grab the entire state so i can serialise it:

`myCerebral.extractState()`

but `extractState` isn't mentioned in the API.md file.

**Comment by christianalfoni** [comment]
I will change extractState to toJS for next release, thanks for the input :-)

**Comment by christianalfoni** [comment]
This is fixed, ready for next release
