### ISSUE TITLE
is cerebral-immutable-store still supported?

### ISSUE THREAD

**Issue by EatYourSpinach** [christianalfoni/cerebral#125]
I'm getting errors when trying to use that as my store with cerebral 0.21.
'cannot read property 'get' of undefined' when I call controller.get(). Let me see if it works with other stores

**Comment by Guria** [comment]
nope, it was deprecated since it has perfomance issues

**Comment by EatYourSpinach** [comment]
thanks. Is baobab recommended now, if we our storage to be based on regular objects?

**Comment by bfitch** [comment]
Yep. Use [cerebral-baobab](https://github.com/christianalfoni/cerebral-baobab). :smile:

**Comment by EatYourSpinach** [comment]
will do thanks!
