### ISSUE TITLE
chrome debugger not working

### ISSUE THREAD

**Issue by EatYourSpinach** [christianalfoni/cerebral#126]
I'm using the latest version of cerebral and the debugger, and I'm firing one test action on page load.
State updates fine, but the cerebral tab in chrome is blank. 
Also, would it be better to raise this type of issue in the gitter discussion, or here is fine?

**Comment by christianalfoni** [comment]
You will get a quicker response on gitter :-)

Make sure you restart the browser. That is usually the issue. Let me know if it does not work and we can look more into it :+1:

**Comment by acramatte** [comment]
For the record: I had a similar issue and it turned out to be that messages passed to the debugger were not stringified. In my case, the issue was fixed by bumping cerebral to 0.21.0

Hope that helps. 

Thanks again for the help.

**Comment by EatYourSpinach** [comment]
I'm using 0.21.0 version of cerebral, Version 46.0.2490.80 (64-bit) of chrome on OS X.

**Comment by christianalfoni** [comment]
Hi @EatYourSpinach, could you share some code with us? And could you try going to: www.christianalfoni.com/todomvc and verify that the debugger works there?

**Comment by EatYourSpinach** [comment]
todomvc works, so it must be something with my code. I'll look more carefully at the todomvc code.
I'm creating my controller like this:
```
import Controller from 'cerebral';
import Model from 'cerebral-baobab';

const state = {	
	itemDetails: {},
	components: {}
};

export default function () {
	const model = Model(state);
	const controller = Controller(model);
	
	return controller;
}
 ```

**Comment by christianalfoni** [comment]
Ah, okay, that is good to know. Lets figure this out :-)

How does your render call to React look like? How do you use the controller with your app and components?

**Comment by EatYourSpinach** [comment]
Well, I'm actually not using react at all...I'm stuck with polymer for the moment. I'm trying to port application logic over to cerebral and then migrate to react.
In my index.js file I have:
```
import createController from './common/controller';
// just an object with signals
import hardwareSignals from './hardware/hardwareSignals';

const controller = createController();
// iterate object keys adding signals
util.createSignalsFromMap(controller, hardwareSignals);

window.controller = controller;
```
then in my test page I have:
```
controller.on('change', function () {
            var newState = controller.get();
            console.log('state changed:', newState);
            template.loading = newState.loading;
            template.backgroundLoading = newState.backgroundLoading;
           ...

        }); 
        controller.signals.showClusterClicked();
```

**Comment by christianalfoni** [comment]
Aha, I see, that is the reason I believe. You have to fire up the devtools manually.

So run: `controller.devtools.start()` before running the app and I think you will be okay :-)

**Comment by EatYourSpinach** [comment]
cool that worked! Thank you very much! Cerebral and polymer seem to get along just fine so far.

**Comment by christianalfoni** [comment]
It is really cool that you check this out. Please create a Polymer issue on the repo when you got some more experience. We can create a UI package for it :-)
