### ISSUE TITLE
Optional localStorage / debugger

### ISSUE THREAD

**Issue by RJ** [christianalfoni/cerebral#13]
Would be nice to be able to disable use of localStorage for persisting the cerebral state, and also to toggle the debugger, without flipping NODE_ENV to production.

Perhaps something like:
<pre>
let cerebral = Cerebral(...);
cerebral.persistence = false;

cerebral.debugger(false);
</pre>

I'd like to add a save button to my debug UI, so I can choose when to persist the cerebral state to localStorage, so a "save now" method on the cerebral would be useful.

**Comment by RJ** [comment]
Calling `JSON.stringify(cerebral.extractState())` takes a few seconds and pegs a CPU in my test app - the stringified version of my state is 2.8MB, so it's a bit impractical to have cerebral auto-save all the time :)

**Comment by christianalfoni** [comment]
Haha, very good point. This should be in there, though have a few other things to fix first :-)

**Comment by mitel** [comment]
+1

**Comment by christianalfoni** [comment]
Okay, this is now ready for next release
