### ISSUE TITLE
Cerebral - Looking in the past, ignored signal showFormStep

### ISSUE THREAD

**Issue by tikiatua** [christianalfoni/cerebral#132]
Hi there,

since updating to cerebral 0.23.0 I constantly experience problems when reloading a window as cerebral is blocking signal processing for signals that can also be processed through cerebral-router. 

Any help would be greatly appreciated.

**Comment by Guria** [comment]
maybe you could show some demo to reproduce?

**Comment by tikiatua** [comment]
The problem seems to be in CreateSignalFactory.js on line 37.

```javascript
signalStore.getCurrentIndex() < signalStore.getSignals().length - 1
```

I think this is due to the signal chain having the same signal as firsts and as last element (in my case «showFormStep» with identical parameters). The method signalStore.getCurrendIndex() will then return 1 instead of the index of the last element. 

I will try to setup an example of the problem.

**Comment by Guria** [comment]
I am was able to reproduce:
```
CreateSignalStore.js:130TypeError: Cannot read property 'module' of undefined(…)
CreateSignalStore.js:131CEREBRAL - There was an error remembering state, it has been reset
CreateSignalFactory.js:39Cerebral - Looking in the past, ignored signal coreAppMounted
CreateSignalFactory.js:39Cerebral - Looking in the past, ignored signal dashboardMounted
```

**Comment by christianalfoni** [comment]
Hi there,

Thanks for checking this. Would it be possible to paste in a simple signal setup which provokes this? I will have a quick look into it and fix it. Seems to be a scenario where the index is not updated inside the store, while the number of signals are.

**Comment by Guria** [comment]
@christianalfoni in my case there was an error while remembering (don't found a reason yet)

**Comment by christianalfoni** [comment]
Hm, okay, let me check here a bit too

**Comment by Guria** [comment]
It always caused while remembering last signal

**Comment by christianalfoni** [comment]
Hm, strange, doing that on our project and there is no problem. Let me try the todomvc app

**Comment by Guria** [comment]
It fails somewhere in wrappedSignal in router

**Comment by christianalfoni** [comment]
Hm, no, does not happen there either. Is the "remember" check still in the router?

**Comment by Guria** [comment]
I found a problem. Will try to fix soon

**Comment by christianalfoni** [comment]
Ah, great, thanks!

**Comment by Guria** [comment]
The reason is that while remembering stored route object is passed to input.
If signal was triggered manually it will have `route: {url:'/url'}` injected to input.
While remembering wrapped signal get this injected initially so it tricked to 'think' that call was triggered from route and tries to copy `params` from `route.params` to `input`.
I already have some refactoring on this part. I'll make a quick fix and publish soon.

**Comment by Guria** [comment]
fixed `cerebral-router@0.7.3` published to npm.

**Comment by christianalfoni** [comment]
Cool! Great stuff @Guria :-)

**Comment by Guria** [comment]
thanks @tikiatua for great finding

**Comment by tikiatua** [comment]
Hey guys,

many thanks for fixing this so fast.
