### ISSUE TITLE
name spacing signals

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral#20]
Name space signals with dot notation

**Comment by christianalfoni** [comment]
This is now in there

**Comment by christianalfoni** [comment]
Released!

**Comment by tnrich** [comment]
Hey @christianalfoni, is there an api doc with explanations of the different features of cerebral? I seem to remember seeing one at one point but can't seem to find it now. Maybe you could make a link to it from the README.md for the main cerebral github page.

**Comment by christianalfoni** [comment]
Hi @tnrich ,

There actually is a link at the very top of the README, though it is quite small... quite embarrassing as probably more people have overlooked it :-) Have made it clearer now!
