### ISSUE TITLE
Todomvc issues

### ISSUE THREAD

**Issue by idream3** [christianalfoni/cerebral#21]
Hi @christianalfoni 

Testing out http://christianalfoni.com/todomvc/ I found some issues with recording and the debugger.

Reproduced a crash consistently by adding items, hitting record, adding more items, playing back, then console errors appear when scrubbing with the debugger timeline.

See attached console screenshots (wish I could be of more help but don't have access to code :))

![screen shot 2015-06-01 at 11 58 05 am](https://cloud.githubusercontent.com/assets/1082632/7904587/3736055c-0856-11e5-846d-2e48f0f6be88.png)
![screen shot 2015-06-01 at 11 59 22 am](https://cloud.githubusercontent.com/assets/1082632/7904588/3738ef88-0856-11e5-81c1-aead6134119c.png)

**Comment by christianalfoni** [comment]
Hi there! 

Thanks, there will be a new version of the recorder very soon. A lot of work has been done, so hopefully this stuff will be fixed :-)

**Comment by christianalfoni** [comment]
Since new version of Cerebral is released the current TodoMVC demo is irrelevant. Let me know if you try out recorder and experience issues on the demo included in repo :-)
