### ISSUE TITLE
Composing state from already composed state

### ISSUE THREAD

**Issue by tnrich** [christianalfoni/cerebral#26]
Hey Christian, 

I had one main question and a couple smaller ones. 

Is it possible for a composed state function to listen to another composed state lookupState. For example, is the following possible?: 

import Cerebral from 'cerebral';

    let visibleTodosThatStartWithTheLetterA = function () {
      return {
        initialState: [],
        lookupState: ['visibleTodos'],
        get(cerebral, lookupState, refs) {
          return lookupState.visibleTodos.filter(function (visibleTodo) {
            if (visibleTodo starts with A) { //pseudocode
              return true
            }
          })
        }
      };
    };

    let visibleTodos = function () {
      return {
        initialState: [],
        lookupState: ['todos'],
        get(cerebral, lookupState, refs) {
          return refs.map(function (ref) {
            return lookupState.todos[ref];
          });
        }
      };
    };

    let cerebral = Cerebral({
      todos: {},
      visibleTodos: visibleTodos,
      visibleTodosThatStartWithTheLetterA: visibleTodosThatStartWithTheLetterA,
      count: 0,
      newTodoTitle: ''
    });

Also, what determines what's inside the refs object that is being passed to the get() function? Is it based on what's in the lookupState?

Finally, say your cerebral was nested:
    let cerebral = Cerebral({
      todos: {
        urgentTodos: [],
        regularTodos
      },
      visibleUrgentTodos = visibleUrgentTodos
    });

Would this be the proper syntax for accessing the 'urgentTodos' property, where the lookupState is an object?

    let visibleUrgentTodos = function() {
      return {
        initialState: [],
        lookupState: {
          urgentTodos: ['todos', 'urgentTodos']
        },
        get(cerebral, lookupState, refs) {
          return refs.map(function(ref) {
            return lookupState.urgentTodos[ref];
          });
        }
      };
    };

Thanks a bunch!

**Comment by christianalfoni** [comment]
Hi @tnrich !

1. A state using a mapping function works just like normal state, so composing mapping functions should not be a problem. That said, I have not been testing those scenarios yet :-) You could end up in a circular dependency of course, and that is definitely not taken care of yet, but yeah... you should not have circular dependencies. Would be nice with an error though :-)

2. The "refs" argument is the value of the state. So whatever you put/change on the path "visibleTodosThatStartWithTheLetterA" will be the third argument, in this case "refs". Same for "visibleTodos"

3. Yup, your nesting is correct :-)

Let me put the composition of mapping functions on the next release. I will test them and throw error on circular occurrences

**Comment by tnrich** [comment]
Hey Christian, 

Thanks for the responses! Much appreciated 

Just to be sure I'm getting it, the 'refs' argument is the previous state of whatever piece of the tree you're setting. Is that right?

Also, to clarify, the composing functions will trigger an update after they've finished calculating themselves which should trigger any listening composing functions to update themselves. Is that also correct?

**Comment by marbemac** [comment]
This would be amazing. It's not working quite yet. I've created an example case at my cerebral-boilerplate fork:
https://github.com/marbemac/cerebral-boilerplate

Spin that up, click the variables link at the bottom of the page, then click "set current user". As you'll see in the cerebral state tree, currentVariables is derived from currentUser (which is itself a mapping function). currentUser is calculated correctly when its lookupState changes, but currentVariables is not.

**Comment by tnrich** [comment]
hey @marbemac , thanks for posting the example!

@christianalfoni, do you have a ballpark idea of how difficult it will be to make arbitrarily complex "state composition" function flawlessly? This is definitely one of the most exciting things about this library and baobab, but unfortunately, neither of them are functioning correctly yet (https://github.com/Yomguithereal/baobab/issues/264). I am wondering if there is something inherently complicated about getting such a system to work correctly, or if it is just a matter of fixing a few bugs.

Thanks for you input!

**Comment by christianalfoni** [comment]
Hi @tnrich!

Good question! It might be one of these things that seems simple, but really is not :-) What I believe to be the challenge here is that if Cerebral runs through the mapping functions it has to figure out if one of the mappings affected one of the others, which again requires it to run through all mappings, which again might affect something... so yeah, it might need to create a dependency tree and run the mappings in the correct order. That is a bit complex, but absolutely doable.

I am trying to find some time at the end of my vacation to create a new version of Cerebral with some changes, where I could also look into this. Let me keep you up to date on this!

**Comment by christianalfoni** [comment]
Hi guys,

The latest version of immutable-store supports this functionality and can be used with the e.g. "cerebral-react-immutable-store" package.
