### ISSUE TITLE
Work with React-Router?

### ISSUE THREAD

**Issue by marbemac** [christianalfoni/cerebral#27]
Hey @christianalfoni, this look awesome! Giving it a go this weekend :).

I've been trying to get Cerebral to work with React-Router with mixed results. 

Using the code below, I see a "Cannot read property 'signals' of undefined" error in app.jsx. 

I also get a warning "Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (cerebral) while mounting App (see: http://fb.me/react-context-by-parent)".

Do you have a quick little example repo of cerebral + react-router working with a couple of routes?

main.jsx
```js
import React from 'react'
import router from './router.js'
import cerebral from './store/cerebral.js'
import AppWrapper from './layouts/appWrapper'

var Wrapper = cerebral.injectInto(AppWrapper)

// run the app. this is the entry point for every route
router.run((Root, state) => {
  let app = (
    <Wrapper>
      <Root {...state} />
    </Wrapper>
  )

  React.render(app, document.getElementById('sl-app-container'))
})
```

appWrapper.jsx
```js
import React from 'react'
import CerebralMixin from 'cerebral/mixin'

let AppWrapper = React.createClass({
  mixins: [ CerebralMixin ],

  propTypes: {
    children: React.PropTypes.node.isRequired
  },

  getCerebralState() {
    return {
      loading: ['appLoading']
    }
  },

  componentDidMount() {
    this.signals.appMounted()
  },

  render() {
    if (this.state.loading) {
      return (
        <div className='sl-app-wrapper h-100'>
          Loading...
        </div>
      )
    }

    return (
      <div className='sl-app-wrapper h-100'>
        {this.props.children}
      </div>
    )
  }
})

export default AppWrapper
```

app.jsx
```js
import React from 'react'
import { RouteHandler } from 'react-router'
import CerebralMixin from 'cerebral/mixin'

let App = React.createClass({
  mixins: [ CerebralMixin ],

  getCerebralState() {
    return {
      session: ['session']
    }
  },

  render() {
    return (
      <div className='sl-app h-100'>
        <RouteHandler />
      </div>
    )
  }
})

export default App
```

login.jsx
```js
import React from 'react'
import CerebralMixin from 'cerebral/mixin'

let Login = React.createClass({
  mixins: [ CerebralMixin ],

  getCerebralState() {
    return {
      session: ['session']
    }
  },

  render() {
    return (
      <div>Login Page</div>
    )
  }
})

export default Login
```

routes.jsx
```js
import React from 'react'
import { Route, DefaultRoute } from 'react-router'
import App from './layouts/app'
import Login from './pages/login'

let routes = (
  <Route handler={App} path='/'>
    <Route name='login' handler={Login} />
  </Route>
)

export default routes
```

**Comment by christianalfoni** [comment]
Hi @marbemac !

Awesome :-)

Context warnings is typically because you have two React instances running. Could you check that first?

**Comment by marbemac** [comment]
@christianalfoni It's not that, I wish it were that easy :).

I forked cerebral-boilerplate to use react-router, check it out here:
https://github.com/marbemac/cerebral-boilerplate

You'll see the errors in the console. Let me know what you think! Would love to get this working.

**Comment by marbemac** [comment]
Ok got it! You need to manually pass cerebral down to the react-router handler, and then in your top level layout (App.js in this case), manually set the cerebral context (what you do in createInjector.js).

main.js
```js
let Wrapper = cerebral.injectInto(AppWrapper);

// run the app. this is the entry point for every route
router.run((Root, state) => {
  // Way #3, inject outside of router, use here
  let app = (
    <Wrapper>
      <Root cerebral={cerebral} />
    </Wrapper>
  )
  React.render(app, document.querySelector('#app'))
})
```

App.js
```js
import React from 'react';
import { RouteHandler } from 'react-router';

let App = React.createClass({
  childContextTypes: {
    cerebral: React.PropTypes.object
  },

  getChildContext: function() {
    return {
      cerebral: this.props.cerebral
    };
  },

  render() {
    return (
      <div>
        <RouteHandler />
      </div>
    );
  }
})

export default App;
```

**Comment by mgamperl** [comment]
Thank you for your input I have got it working with react-router and that is great!

But there is one thing i am missing. Do you have any idea how to sync the route changes with the cerebral state and the debugger? 

Thank you for any hints!

**Comment by christianalfoni** [comment]
Hi guys,

I have been working on this project called `reactive-router`, https://github.com/christianalfoni/reactive-router. It tries to make the router just a router which has a lot of benefits I think. Check out more in the repo and yeah... it works with the debugger :-)

Small video presentation here: https://www.youtube.com/watch?v=6tUbnDHq8xs

**Comment by mgamperl** [comment]
I have already seen this, thanks! Will try it in the next days. 👍
