### ISSUE TITLE
Mutations in async signals?

### ISSUE THREAD

**Issue by marbemac** [christianalfoni/cerebral#28]
Must one manage ALL state in cerebral? Take the example below, where I have a login component with a couple of input fields. Rather than adding a new "loginFields" property to the cerebralTree, and adding all the cerebral plumbing to the login component to track input changes, I just call a single signal, "login", with the login payload, on submit. I'd like to set the loading indicator to true, and I do this in it's own signal (session.loading) since I can't mutate the tree in session.create (async). Thus, the payload I'm passing is sent to the loading function, instead of the create function.

Is there a reason we can't do simple mutations in signals that return an async function (perhaps only outside of the returned async function?)? Basically what I want to do is put "cerebral.set(['session', '$loading'], true)" at the top of the session.create function below.

```js
cerebral.signal('login', session.loading, session.create, session.set)
```

```js
handleSubmit(event) {
    event.preventDefault()

    let payload = {
      email: this.refs.email.getDOMNode().value,
      password: this.refs.password.getDOMNode().value
    }

    this.signals.login(payload)
}
```

```js
import Remote from '../remote'

let loading = function (cerebral) {
  cerebral.set(['session', '$loading'], true)

  return arguments
}

let create = function (cerebral, payload) {
  // this is an async function
  return Remote.create(Remote.models.SESSION, payload, false)
}

let set = function (cerebral, result) {
  if (result.data) {
    localStorage.session = JSON.stringify(result.data)
    cerebral.set('session', result.data)
  } else {
    cerebral.set('session', {
      $loading: false,
      $error: result.error
    })
  }

  return result.data
}

export default {
  loading: loading,
  create: create,
  set: set
}
```

**Comment by marbemac** [comment]
@christianalfoni Another option to enable this use case, which is kind of interesting, is to pass arguments down if nothing is returned in the action. So:

```js
cerebral.signal('login', session.loading, session.create, session.set)
```

```js
function login() {
    // this payload needs to be sent through the loading action
    this.signals.login({email: 'foo', password: 'bar'})
}
```

```js
// no return, so any arguments that were passed into this, get forwarded onto the next signal
let loading = function (cerebral) {
  cerebral.set(['session', '$loading'], true)
}

// payload is passed through to this action
let create = function (cerebral, payload) { 
  // this is an async function
  return Remote.create(Remote.models.SESSION, payload, false)
}

let set = function (cerebral, result) {
  if (result.data) {
    localStorage.session = JSON.stringify(result.data)
    cerebral.set('session', result.data)
  } else {
    cerebral.set('session', {
      $loading: false,
      $error: result.error
    })
  }

  return result.data
}

export default {
  loading: loading,
  create: create,
  set: set
}
```

**Comment by christianalfoni** [comment]
Did our hangout session answer these questions? :-) Maybe take a look at next arg-set, return path etc. implementation and move from there?

**Comment by christianalfoni** [comment]
Just closing this, I think we talked about it ;-)
