### ISSUE TITLE
Abort signal chain?

### ISSUE THREAD

**Issue by marbemac** [christianalfoni/cerebral#29]
Is there a way to abort a signal chain? I have a register signal, that tries to register the user, and then after that it logs them in. If the register fails, I don't want to continue down the signal chain. Another option is the ability to call signals from within signals, but this seems like a less than ideal solution that would make it harder to reason about signal chains and how they flow.

**Comment by bfitch** [comment]
This doesn't answer your question directly, but I believe Elm handles failure cases in its `Task` API by chaining an `onError` function: https://github.com/elm-lang/elm-lang.org/blob/master/src/guide/chapters/reactivity.md#error-handling. There are some other options listed too (Maybe and toResult). 

Not sure if @christianalfoni has plans to incorporate something like Tasks into cerebral, but it's at least good to know that there's a nice pattern to handle this generally. :)

**Comment by christianalfoni** [comment]
Hi guys,

Currently a rejected promise will stop the promise chain, but it is really there to catch exceptions. My theory is that any value should be resolved, even failed requests to the server. The reason is that you should act upon it in some way.

Not knowing the complete scenario here, but I would suggest that the "registerUser" failing would resolve a different value to "logInUser" than a successful request. The "logInUser" action could be called something like "logInOrRejectUser". And it would set two different states based on the returned failed/successful value from "registerUser". Does that make sense?

**Comment by marbemac** [comment]
That does make sense, but unfortunately the chain is longer than just one action after the create. With your method, I would need to handle this all the way down the chain.

Also, what I love about the actions is that they're little independent,re-usable pieces, that can be composed in all sorts of ways. Introducing logic specific to another action reduces this awesomeness.

```
tree.signal('register',
  user.current.loadingOn,
  user.create,
  user.set, // here, if create was unsuccessful, the chain should stop..
  session.create,
  session.set,
  api.start,
  proxy.start,
  user.current.loadingOff
)
```

**Comment by JosephClay** [comment]
I agree with @marbemac, what I like about actions is that they handle one thing. Some way to stop the chain so that another signal can handle the change would be ideal to keeping actions from becoming `somethingOrSomething` and `somethingAndSomething`...breaking the single responsibility principal.

A contrived example (based on above):
```
cerebral.signal('register',
    user.current.loadingOn,
    user.createOrHandleFailure,
    user.setIfCreated,
    api.startIfUser
    ...
);
```

**Comment by christianalfoni** [comment]
Hi again guys!

Yeah, you definitely make a good point :-)

I was thinking of something like this:

```js
var registerUser = function (cerebral) {
  return new Promise(function (resolve) {
    request('/register')
      .end(function (err, resp) {
        if (err) {
          resolve(cerebral.signal.STOP);
        } else {
          resolve(JSON.parse(resp.text));
        }
      });
  });
};

cerebral.signal('appMounted', registerUser...);
```

So you have these "special" resolved values that makes the chain behave differently. One such value would stop the chain, an other might "jump to last" (cerebral.signal.LAST), "skip" (cerebral.signal.SKIPNEXT) etc. 

I am a bit unsure about introducing completely new concepts like this... but again, they would give a lot of flexibility.

**Comment by christianalfoni** [comment]
And hi again :-)

I did some more thinking and an alternative here is to allow a "split" at the end of each action flow:

```js
cerebral.signal('appMounted', registerUser, {
  success: [loginUser, doSomethingMore],
  error: displayRegisterError
});
```
With this syntax you get a better overview of the flow. Which again could handle pretty complex flows:

```js
cerebral.signal('appMounted', registerUser, {
  success: [loginUser, doSomethingMore, {
    success: showSuccess,
    error: showError
  }],
  error: displayRegisterError
});
```

The good thing here is that you can read a very complex flow by looking at the signal syntax, which I think is a really good feature of the current implementation. It is very easy to understand the overall flow of the application looking at the signal syntax. A deeper understanding of the flow you get with the debugger.

Anyways, just some initial thoughts :-)

**Comment by idream3** [comment]
Cool!

And hi again :-)

I did some more thinking and an alternative here is to allow a "split" at
the end of each action flow:

cerebral.signal('appMounted', registerUser, {
  success: [loginUser, doSomethingMore],
  error: displayRegisterError
});

With this syntax you get a better overview of the flow. Which again could
handle pretty complex flows:

cerebral.signal('appMounted', registerUser, {
  success: [loginUser, doSomethingMore, {
    success: showSuccess,
    error: showError
  }],
  error: displayRegisterError
});

The good thing here is that you can read a very complex flow by looking at
the signal syntax, which I think is a really good feature of the current
implementation. It is very easy to understand the overall flow of the
application looking at the signal syntax. A deeper understanding of the
flow you get with the debugger.

Anyways, just some initial thoughts :-)

—
Reply to this email directly or view it on GitHub
<https://github.com/christianalfoni/cerebral/issues/29#issuecomment-114408394>
.

**Comment by marbemac** [comment]
@christianalfoni Love it! It also preserves the current syntax, which is nice for everybody who is already building on Cerebral. 

One thing I'd note about actually triggering the error, is that it would be nice to decouple the triggering from promises. Being able to trigger an error in an action that is not async would be useful. Perhaps throwing, returning, or resolving with a js Error triggers the error flow? Maybe not throwing - perhaps just return and resolve, as that keeps the input / output nature of actions consistent.

```js
var registerUser = function (cerebral) {
    if (there is an error) {
      throw new Error('foo')
    }
}
var registerUser = function (cerebral) {
    if (there is an error) {
      return new Error('foo')
    }
}
var registerUser = function (cerebral) {
  return new Promise(function (resolve) {
    request('/register')
      .end(function (err, resp) {
        if (err) {
          resolve(err); // if err is an Error object
          resolve(new Error('bad register!')) 
        } else {
          resolve(JSON.parse(resp.text));
        }
      });
  });
};
```

**Comment by JosephClay** [comment]
@marbemac The current system could still work with non-async actions by returning [`Promise.reject()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject)

@christianalfoni Would *not* declaring a `reject` short circuit the chain then? e.g.:
```js
cerebral.signal('foo',
    doSomething,
    {
      resolve: [...] // if this errors/rejects....
    },
    somethingElse // ...this would not be called
);
```

**Comment by christianalfoni** [comment]
Hi there, 

Think of the `resolve` and `reject` path as being concatenated on to the parent chain... if it exists. So currently a reject will never abort a "parent chain", which I suppose it should not do either?

So a rejection just chooses a path, it has nothing to do with stopping the chain really. I think you would have to construct your chain in such a matter that a reject hits a "dead end". Like:

```js
cerebral.signal('foo',
    doSomething,
    [doSomeAsync, {
      resolve: [somethingElse],
      reject: [] // <- dead end
    }]
);
```
Using the new syntax here

**Comment by christianalfoni** [comment]
Hi there,

Aborting a signal can be done by throwing an error on next release. Or go to "dead end", as the example above, depending on the situation.
