### ISSUE TITLE
Should Cerebral be independent of React?

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral#3]
Cerebral does not really need React, should it be standalone?

Would have to create strategies for injecting the debugger into the different frameworks or create a generic JavaScript version of it.

**Comment by idream3** [comment]
Agree.

There is Deku, a much slimmer and version of React, that was open sourced recently
https://github.com/segmentio/deku

The only React specific code is the mixin right?

**Comment by christianalfoni** [comment]
Deku looks like an interesting project! The challenge of supporting more libraries is the debugger. Currently it is written in React and would have to be written in the specific frameworks or a generic plain JavaScript version. And would need to find a good way to inject it. It is quite elegant in React as you create this wrapper which exposes the cerebral on the context and injects the debugger. Not quite sure to do it as elegantly in other solutions. Hm hm...

**Comment by idream3** [comment]
Ahh I see. Maybe energy is better spent focusing on other areas for now :)

**Comment by christianalfoni** [comment]
Yeah, I agree. Lets close this for now. As there is still much work to get Cerebral stable :-)

**Comment by henri-hulski** [comment]
:+1: for Deku integration.

**Comment by Guria** [comment]
Cerebral already not tied to React. You can use it with whatever view layer you want.

**Comment by henri-hulski** [comment]
Sure. I thought this thread is from this year. 

So for using Deku as view layer do I need to write a layer package similar to cerebral-view-react? 

Does someone tried to use Cerebral with Deku and have any hints?

**Comment by Guria** [comment]
I have tried a deku last friday. Seems it will be pretty easy to make integration, but can provide any hints only tomorrow. Package is not a requirement, but would be great to have it.

**Comment by Guria** [comment]
Basic hints: put cerebral state (controller.get) to context and put signals (controller.getSignals) to dispatcher.

**Comment by Guria** [comment]
@henri-hulski Here is 2 possible approaches:
#### expose signals through dispatch function
```js
import { dom, element, createApp } from 'deku'
import Controller from 'cerebral'
import Model from 'cerebral-model-baobab'
import Devtools from 'cerebral-module-devtools'

let controller = Controller(Model({
  foo: 'bar'
}))

controller.addSignals({
  smthClicked: [ ({state}) => { state.set('foo', 'baz') } ]
})

controller.addModules({
  devtools: Devtools()
})

function dispatch (signalName, payload) {
  controller.getSignals(signalName)(payload)
}

const mountNode = document.getElementById('app')
const render = createApp(mountNode, dispatch)

function refresh(Component) {
  render(<Component />, controller.get())
}

function App ({ context, dispatch }) {
  function onClick (e) {
    dispatch('smthClicked', { x: e.x, y: e.y })
  }

  return (<div onClick={onClick}>{context.foo}</div>)
}

refresh(App)

controller.on('change', function () {
  refresh(App)
})
```

#### expose signals through context
```js
import { dom, element, createApp } from 'deku'
import Controller from 'cerebral'
import Model from 'cerebral-model-baobab'
import Devtools from 'cerebral-module-devtools'

let controller = Controller(Model({
  foo: 'bar'
}))

controller.addSignals({
  smthClicked: [ ({state}) => { state.set('foo', 'baz') } ]
})

controller.addModules({
  devtools: Devtools()
})

const mountNode = document.getElementById('app')
const render = createApp(mountNode)

function refresh(Component) {
  render(<Component />, {
    state: controller.get(),
    signals: controller.getSignals()
  })
}

function App ({ context }) {
  function onClick (e) {
    context.signals.smthClicked({ x: e.x, y: e.y })
  }

  return (<div onClick={onClick}>{context.state.foo}</div>)
}

refresh(App)

controller.on('change', function () {
  refresh(App)
})
```
----
Also you can try to write a HOC to expose only needed parts of state tree to each component:
```js
import {Component} from 'cerebral-view-deku'

function App ({ state }) {
  return <div>state.foo</foo>
}

export default Component(App, {
  // state.get().bar.baz would be exposed as state.foo inside component
  foo: 'bar.baz'
})
```

**Comment by Guria** [comment]
BTW, HOC could also expose signals as well:
```js
import { dom, element, createApp } from 'deku'
import Controller from 'cerebral'
import Model from 'cerebral-model-baobab'
import Devtools from 'cerebral-module-devtools'
import {Component} from 'cerebral-view-deku'

let controller = Controller(Model({
  foo: 'bar'
}))

controller.addSignals({
  smthClicked: [ ({state}) => { state.set('foo', 'baz') } ]
})

controller.addModules({
  devtools: Devtools()
})

const mountNode = document.getElementById('app')
const render = createApp(mountNode)

function refresh(Component) {
  // do not expose anything to context
  render(<Component />)
}

let SomeComponent = Component ({ foo: 'foo' }, function App ({ signals, state }) {
  // there is access to signals and partial state
  function onClick (e) {
    signals.smthClicked({ x: e.x, y: e.y })
  }

  return (<div onClick={onClick}>{state.foo}</div>)
})

function App () {
  // there is no access to signals and state
  return (<SomeComponent />)
}

// render
refresh(App)
controller.on('change', function () {
  refresh(App)
})
```
