### ISSUE TITLE
unset working correctly?

### ISSUE THREAD

**Issue by marbemac** [christianalfoni/cerebral#31]
Should the following work?

```js
let tree = Cerebral({
  unsetTest: {
    foo: 'bar',
    removeMe: 'please'
  }
})

tree.unset(['unsetTest', 'removeMe'])
```

The normal use case for this would be removing a model on delete. tree.unset(['projects', '123']).

It doesn't seem to work at the moment. You can try it out on my fork:
https://github.com/marbemac/cerebral-boilerplate

**Comment by christianalfoni** [comment]
Weird, should work, let me check it!

**Comment by christianalfoni** [comment]
Does this work now?

**Comment by christianalfoni** [comment]
This is immutable-store issue if it still does not work, so have to set up an issue there instead
