### ISSUE TITLE
Inject React instance

### ISSUE THREAD

**Issue by ericelliott** [christianalfoni/cerebral#32]
Having multiple versions or instances of React in an application is a [frequent](https://github.com/gaearon/react-hot-loader/issues/32#issuecomment-60043061) [source](https://github.com/KyleAMathews/coffee-react-quickstart/issues/10#issuecomment-50655116) [of](https://github.com/gaearon/react-document-title/issues/1#issuecomment-60241045) [trouble](https://github.com/clayallsopp/react.backbone/issues/26) (see [Two Weird Tricks that Fix React](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375)), and the [handling of peerDependencies is currently in flux](https://github.com/npm/npm/issues/6565).

Would it be possible to take React as an injected dependency instead of depending on it directly?

**Comment by troutowicz** [comment]
:+1:

While on the topic of dependency injection, Cerebral may be interested in a new alternative for `React.createClass`... [react-stampit](https://github.com/stampit-org/react-stampit). It has been designed with dependency injection in mind.

**Comment by ericelliott** [comment]
:+1: for react-stampit

**Comment by JosephClay** [comment]
:+1: for react-stampit

**Comment by christianalfoni** [comment]
Hi guys and thanks for the input!

As I understand NPM 3 will force you to explicitly install peer dependencies? That said, there is of course nothing wrong with supporting React injection :-)

Let me put this on the list. Cerebral is in pending state at the moment, as it is being used to develop a service. Release of Cerebral and further development will continue when the service is released!

Thanks for the feedback!

**Comment by ericelliott** [comment]
:+1:

**Comment by christianalfoni** [comment]
Hi again!

Since Cerebral took a turn, hopefully for the better, it no longer depends on React. So I will close this issue :-)
