### ISSUE TITLE
Lacking documentation and simple examples

### ISSUE THREAD

**Issue by guerch** [christianalfoni/cerebral#38]
First, thank you for publishing your work!, but here comes some constructive criticism from a beginner:

There is no clear way to begin a simple application, the only boilerplate project i found is outdated and serves to confuse some concepts even more.  

There is no sequence in the readme to follow that can make you have a working simple cerebral app.  It starts showing a bunch of Cerebral packages, it does not explain their purpose (i figured it to be an adapter to a store that also has some bootstrapping code, none explained).  by trying to replicate the code in cerebral-react-immutable-store, on a new simple app only throws errors (using Decorator Syntax).

The video just glosses over some concepts and does not explain how to build a simple cerebral app, it explains some concepts of cerebral that can be grasped but other stuff remains hidden.

The demo on cerebral of todo-mvc has no explanations or pertinent comments, it bootstraps a custom package in a way not mentioned anywhere (using a wrapper class with childContexTypes and getChildContext) ,and that reminds me there is no api documentation, it also uses a StateComponent thing, that i presume has to do with the record function, its neat, but this further obscures what is needed to create a cerebral app.

I am sold on the concept, but a simple boilerplate for cerebral (with a custom package) and other boilerplates for cerebral-react-immutable-store, would help tremendously, preferably explaining all the details.

For some source code is documentation enough, i am unfortunately, i bit more limited. 
I will try to read all over this again tomorrow, perhaps i will wrap my head around it eventually, but for now i cant help but be somewhat confused.

**Comment by tikiatua** [comment]
Hi @guerch 

You are certainly right in respect to the currently limited documentation. Please keep however in mind that cerebral was completely restructured and decoupled just recently - and might not even yet have a stable api.

We are already successfully using an earlier version in production for a small application and managed to set it up just fine using the videos and documentation at hand and adding some small tweaks to the source code.

I am sure the documenation will be improved once the api is more stable.

**Comment by christianalfoni** [comment]
Hi guys!

Yeah, it is still lacking, though I am working on it :-)

If you check out the `cerebral-react-immutable-store` repo you should see a much better explanation now. A video introducing it will be released later today also.

Thanks for pointing out where things slipped, it really helps going in the right direction with the documentation :-)

**Comment by christianalfoni** [comment]
I hope the new video and documentation is to your liking! :-) Let me know if there are certain parts that needs more explanation, thanks!

**Comment by guerch** [comment]
@christianalfoni, incredible video!, realy good stuff, thank you!
