### ISSUE TITLE
Component update only when relevant state changes?

### ISSUE THREAD

**Issue by jardakotesovec** [christianalfoni/cerebral#39]
Hi,
I am exploring cerebral, saw the videos, but did not find information if components get updated only if state they requested is changed or they are updated simply on any state change.

For example, in this case would be nice if component refresh only when on of these three properties in state changes:
```
@Cerebral({
  isLoading: ['isLoading'],
  user: ['user'],
  error: ['error']  
})
```

So wondering if something like this is implemented or its planned.

Thank you! 
Btw videos you created are very helpful make first steps, well done!

**Comment by tikiatua** [comment]
Some short tests indicate, that the component does only update if one of the connected properties changes, but not if other properties in the state change.

**Comment by christianalfoni** [comment]
Hi guys,

You could put the PureRenderMixin on the component using the decorator, but I suppose it would be okay to do a quick check on the wrapper. I was not sure if it should be there by default, but since you bring it up I have given it some more thought... it should be there :-)

**Comment by christianalfoni** [comment]
And hi again, the repo is now updated with a `shouldComponentUpdate` method :-)

https://github.com/christianalfoni/cerebral-react-immutable-store/releases/tag/v0.4.0
