### ISSUE TITLE
Thoughts on Cerebral with the different Stores

### ISSUE THREAD

**Issue by larryhengl** [christianalfoni/cerebral#41]
Hi Christian, great stuff here.  Really appreciate you putting it out there, with the great vids too.
I'm eager to try Cerebral on my next project.  As I approach it I am also wondering which Store to use.  I have been using Baobab on my last couple of projects, and I know you've used Baobab a bunch in the recent past too.  Can you share your experience/preferences so far on using say Baobab or any of the immutable store libs with Cerebral?  With Baobab you get cursors/facets...does that become less important when using Cerebral eventing, etc?  Which store tends to "feel" better when plugging into Cerebral?
Many thanks!
:Larry

**Comment by christianalfoni** [comment]
Hi @larryhengl!

That is a very good question indeed :-)

Currently I have only played with my own `immutable store` project and recently added the `baobab` package. I really like Baobab and I think version 2 of Baobab will fit like a glove with Cerebral. Currently the facets does not seem to be completely implemented yet, so the facets are not working as of now with the baobab package. You can follow an issue on that here: https://github.com/Yomguithereal/baobab/issues/324.

So right now, to get the full experience I would use the `immutable-store` package. That project also has facets, though they are called "mappings". They work the same way. Read more about that here: https://github.com/christianalfoni/immutable-store#mapping-state :-)

Generally there is not much difference in how state is stored, it is more how you can compose that state using facets etc. that becomes more of a decision factor I think. With extremely mutation heavy projects there might be an issue of performance too.

I still have `immutable-js` to try out, which probably will be the fastest, though it does not have facets/mappings. Maybe a "network" of observables as the "model layer" would also be a kinda cool approach. Maybe even Redux could be used. Lots to try out :-)

**Comment by christianalfoni** [comment]
Btw, Baobab cursors becomes quite irrelevant when using Cerebral. Also the eventing. The reason is that the Cerebral mutation hooks will change the state for you and optimize updates to the components with its own mixins. The eventing is also optimized as it is triggered when a signal is done running, not batched up on next event loop. Does not make much difference, but it is actually faster and more predictable ;-)

So basically all you need to do is define your state, use the Cerebral mutation methods and use the state in your components. You do not need to wire up cursors.

As we are talking about it, the cursors was really only important when baobab was mutable. Now that baobab is immutable it is a lot easier to just emit the whole tree on a change and check inside the components if that value has changed shallowly (in the mixins).

**Comment by larryhengl** [comment]
Great insight, @christianalfoni.  Thanks for sharing your thoughts and experiences on this topic.

I like Baobab's facets for deriving sets of values from state (or cursors or other facets), and I've also used them the same way as your doc example of projectRows in immutable-store mappings.  But mappings looks like it steps that up notch with import/export.  Also seems that mappings can map over it's values *or* it's deps, depending on what you are wanting to do.  Nice.

Looking forward to seeing how Baobab v2 shapes up.
Kinda curious how Redux could fit in here too.  :-)

But for now, thanks to your feedback (and those cool vids and blog posts), I may start my next app with something like:
immutable-store (M), react (V), cerebral (C), reactive-router (R)
(and with that webpack, livereload, debugger goodness thrown in...sheesh, fun stuff).

Thanks again for sharing all your work!

:L

**Comment by christianalfoni** [comment]
Hi again!

Yup, you are right, immutable-store can map of mapped state :) And it supports import/export which is important in regards of recording state, if you want to use that feature.

I actually just released new version of baobab package where facets work.

Hehe, yeah, it is a good time to do web development and you are very welcome :-D

**Comment by christianalfoni** [comment]
Just closing this, reopen if more questions :-)
