### ISSUE TITLE
How to conditionals in signals

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral#42]
Let us just start out with an example:

```js
controller.signal('appMounted', isAdmin, [getAdminData]);
```

Very often you have some conditional in your action chain. The question is, where does this conditional belong?

```js
onMount: function () {
  if (this.state.isAdmin) {
    controller.signals.appMounted();
  }
}
```
It could have been handled at the call site, but then you have to make sure each callsite does this check.

Maybe we could configure the signal?

```js
controller.signal({
  name: 'appMounted',
  filter: isAdmin
}, [getAdminData]);
```

But what if you wanted multiple conditionals... maybe even inside the chain somewhere?

```js
controller.signal('appMounted', [getUser, getItems], isAdmin, [getAdminData]);
```

Or maybe this actually belongs with the action?

```js
const getAdminData = function (args, state, promise) {
  if (state.get('isAdmin') {
    args.utils.ajax.get('/admindata').then(promise.resolve).catch(promise.reject);
  } else {
    promise.resolve({data: null});
  }
}
```

Any thoughts and scenarios would be appreciated :-)

Currently my cents on this is:

1. An admin signal should never be triggered by the UI if the user is not an admin... as that button (or whatever) should not be visible. The ajax request would also fail, as the user really is not an admin

2. If a signal could be triggered with an admin/non admin I think the action should handle it, resolving "no data" if the user is not admin and getting data if it is an admin

**Comment by Guria** [comment]
```js
const checkRole = function(args, state){
  if (this.state.isAdmin) {
    controller.signals.adminLoggedIn();
  }
}

controller.signal('appMounted', [getUser, getItems], checkRole);
controller.signal('adminLoggedIn', [getAdminData]);
```

**Comment by christianalfoni** [comment]
Hi @Guria and thanks for the suggestion! Letting a signal trigger a new signal has been discussed earlier too actually. Though it reads well in your example it will hide itself when all you see in your code is:

```js
controller.signal('appMounted', [getUser, getItems], checkRole);
// other signals
controller.signal('adminDetected', [getAdminData]);
```
It is difficult to see the flow. It is also a matter of debugging and potential loops when one signal triggers an other. So yeah, it would work, but not ideal I think :-)

Lets play around with the idea some more first!

**Comment by garth** [comment]
What about using the same convention as when calling a signal synchronously and prefix the array with `true` and use the return value of the decisionAction to determine the path:

```js
function getUserRole(args, state) {
  return state.get('userRole'); // can be one of admin, moderator or user
}

controller.signal('appMounted',
  [getUser],
  [true, getUserRole, {
    admin: [getAdminData],
    moderator: [getModeratorData],
    user: [getStandardUserData]
  }],
  finalAction
);
```

If there's no match in the decision hash then we just move on to the `finalAction`. Effectively making `controller.signal('name', action);` and `controller.signal('name', [true, action, {}])` equivalent.

I'm not sure I really like the `true` prefix, but since it's already used when sending input element signals it kinds of matches.

**Comment by garth** [comment]
@christianalfoni I like your point about not triggering admin signals, perhaps `isAdmin` is not the best example.

The thing that I really like about signals is that they read like a nice story, you can see the beginning, the middle and the end, and that is reflected in the debugger also. If conditionals are handled entirely in the actions or in the app logic that calls the signals then you may loose the overview that signals should provide.

Cerebral may already have primitives to support conditional paths, or in some cases we may have to change they way that we think about a problem to more of a "reactjs" way , but  it would still be nice to keep overview that the signal definition currently provides when dealing with more complex scenarios.

**Comment by christianalfoni** [comment]
I think it is really important to keep the readability of signals, as that really is its power. The async resolve/reject is at the "edge" of readability, but on the other side it is necessary to provide paths.

But as you also point out, its the way you think about it. So for example:

```js
controller.signal('appMounted',
  [getUser],
  [true, getUserRole, {
    admin: [getAdminData],
    moderator: [getModeratorData],
    user: [getStandardUserData]
  }],
  finalAction
);
```
Could be expressed as:
```js
const getUserData = function (args, state, promise) {
  const user = state.get('user');
  args.utils.ajax.get('/userdata', {type: user.type}).then(promise.resolve).catch(promise.reject);
};
controller.signal('appMounted',
  [getUser],
  [getUserData],
  finalAction
);
```

So yeah, maybe we should just keep hitting this with examples and try to challenge the way we think about it. It should be an extremely useful and common use case to add more syntax complexity to a signal I think :-)

The natural step with Cerebral is to allow a reactive controller layer. I chose not to go down that path because most developers think imperatively. But chaining actions gives this functional flavour and the name of a signal is "reactive". So when RxJS gets a better foothold with common developers, I think Cerebral will get a purely reactive controller. Which will let you manipulate the signals more... it needs a lot of research though, thats for sure :-)

**Comment by Guria** [comment]
@christianalfoni got your point.

I don't like idea of massive action paths when logic pretty different in branches of conditionals. So I would prefer to split it into different signals. What if we declare signals triggered in signals in `controller.signal` declaration (for example with a string value)?

I like @garth suggestion to use syntax of redirecting async actions since it also some sort of conditionals. But I'll suggest to treat an object in actions array as conditionals branches declaration for previous action. Leaving opening bracket on the same string with action would help to increase readability.

Getting all together:
```js
function checkAttemptsExceeded(args, state) {
  return state.get('$attemptsCounter') > 5;
}

controller.signal('appMounted',
  [getUser, {
    reject: [ 'loginNeeded' ]
  }],
  [getItems, {
    resolve: [ 'dataLoaded' ],
    reject: [ 'dataLoadingErrorOccured' ]
  }],
  finalAction
);

controller.signal('dataLoadingErrorOccured',
  increaseAttemptsCounter,
  checkAttemptsExceeded, {
    'true': displayAttemptsExceededMessage,
    'false': [
      displayTroublesMessage, [getItems, {
        resolve: [resetAttemptsCounter, hideTroublesMessage, 'dataLoaded'],
        reject: 'dataLoadingErrorOccured'
      }],
    ]
  },
);

controller.signal('dataLoaded',
  runSomeAggregations,
  checkSomeCondition, {
    'case a' : ['someSignal'],
    'case b' : ['anotherSignal']
  }
);

controller.signal('loginNeeded', displayLoginModal);
```

**Comment by christianalfoni** [comment]
Hi @Guria and thanks again for suggestions! :-)

Using a string does increase readability! About redirecting to a different signal I was thinking of rather grouping actions. The reason is that `dataLoaded` in this case is not a signal a VIEW layer would trigger, its rather just a group of actions to run. That would be exactly what the debugger would do too, it would not indicate a new signal, but rather concatenate the actions from the next signal definition.

So we can introduce composition of actions:

```js
const $doMoreThings = controller.action(
  runSomeAggregations,
  checkSomeCondition, {
    'case a' : [doSomething],
    'case b' : [ doSomethingElse ]
  }
);

controller.signal('dataLoadingErrorOccured',
  increaseAttemptsCounter,
  checkAttemptsExceeded, {
    'true': displayAttemptsExceededMessage,
    'false': [
      displayTroublesMessage, [getItems, {
        resolve: [ resetAttemptsCounter, hideTroublesMessage, $doMoreThings ],
        reject: [ setError ]
      }],
    ]
  },
);
```

The suggestion on arbitrarily adding an object to the signal is actually a pretty good idea. It just says "break here and choose a path". It would also conform the signature of sync/async actions as the new syntax would have to be something like:

```js
const SUCCESS = 'SUCCESS';
const ERROR = 'ERROR';

const syncAction = function (args, state, next) {
  next(SUCCESS, {foo: 'bar'});
}

const asyncAction = function (args, state, next) {
  next(ERROR, {foo: 'bar'});
}
```

Now this looks a lot more traditional middleware too, which is good. So yeah, we would just remove the special {resolve: [], reject: []} for promise and generally introduce {} to set paths. The action before it needs to define the path using the `next` resolver.

It needs some more work, but what do you think?

**Comment by idream3** [comment]
@christianalfoni 

Ahh, you beat me to it :)

Was also going to suggest removing the special resolve/reject object and make it abitrary depending on the previous actions decision.

**Comment by garth** [comment]
I think that the object/middleware/next idea is a winner.

1. Does every action have to call `next()` or only those before an object? (not calling `next()` could be good way to cancel the signal)
2. If the object doesn't have the next key should the object be skipped?
3. Should there be an optional `default` key?

**Comment by idream3** [comment]
Quick thought - the `next()` should be in every action and you could use it to exit an action early, like you `break` out of a for loop. 

```javascript
const syncAction = function (args, state, next) {
if (!condition)  next();
state.set(...)
}
```

**Comment by christianalfoni** [comment]
Hi guys and thanks for the feedback :-)

I have created two new issues, splitting it into two feature requests:

1. "Action Groups": #44 
2. "Conditionals": #43

**Comment by christianalfoni** [comment]
@idream3 You would have to return the "next" or the rest of the code would actually run. This is a gotcha with middleware in general. But yeah, you could do that :-) 

I will close this thread and let us continue on the two new issues.

**Comment by Guria** [comment]
Hi @christianalfoni. You made a great work in latest release.
I still can't see how to make a conditional with attempts counter like in my suggestion where was recursive call to `'dataLoadingErrorOccured'` until `checkAttemptsExceeded` action would be outputed to `true` path.

**Comment by christianalfoni** [comment]
Hi @Guria!

Sorry about not addressing that example. Allowing a signal to trigger a different signal has some challenges: 

1. It can quickly cause loop conditions that freezes the application
2. It encourages complexity that might be unnecessary. What I mean about that is that if signals allows you to jump to other signals you also have to jump to other signals when reading the code. And if you jump to a different signal in the middle of an other signal you have to compose in your head how that signal chain actually looks, as it is a combination of two signals... where the second signal might jump to an other signal again... it can become quite messy
3. The debugger will have a hard time explaining you what is actually going on, which says something about the complexity it causes :-)

That said you could say that the responsibility is in the hands of the developer, and that might be true :-) But I do not want to go down a path that can cause so much complexities without really really really thinking it through.

So let us play around with the example a bit more, see if we can find other ways to handle the scenario.

I think this would work and I think it reads better too... my opinion ;-) :

```js
function loadData (input, state, output) {
  if (state.get('doRetry') {

   input.utils.ajax('/data', {
     retryCount: 5
   })
   .success(output.success)
   .error(output.error);

  } else {

    input.utils.ajax('/data')
      .success(output.success)
      .error(output.error);

  }
};

controller.signal('loadDataClicked',
  [
    loadData, {
      success: [setData],
      error: [
        displayRetryMessage, 
        setRetry,
        [
          loadData, {
            success: [unsetRetry, setData],
            error: [unsetRetry, displayFailedMessage]
          }
        ]
    }
  ]
);
```

**Comment by Guria** [comment]
Thanks. Great example. It definitely meets my expectations how it should looks like.

**Comment by christianalfoni** [comment]
Ah, great @Guria. You might do it like this too:

```js
controller.signal('loadDataClicked',
  [
    loadData('/something'), {
      success: [setData],
      error: [
        displayRetryMessage,
        [
          loadData('/something', {retries: 5}), {
            success: [setData],
            error: [displayFailedMessage]
          }
        ]
    }
  ]
);
```

It just shows how you can use factories to reuse functions even more. Kinda cool... :-)

**Comment by Guria** [comment]
Yeh cool. It seems you forgot to call `hideRetryMessage` action in both examples ;)

**Comment by christianalfoni** [comment]
Ah, yeah, my bad :-) I plan to create a new video clip today using your example here. I think it is a great example to show off a complex flow and use action factories. A long with the new input/output stuff
