### ISSUE TITLE
New Feature: "Top Level Array"

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral#44]
To allow easy composition of signals, we will make the top level an array.

```js
const $actionGroup = [
  action1,
  action2,
  [action3]
];

controller.signal('somethingHappened', [specialAction].concat($actionGroup));
controller.signal('somethingElseHappened', $actionGroup);
```

This requires breaking API change though, as the top level will need to be an array to support:

```js
controller.signal('somethingHappened', [ 
  [asyncAction] 
]);

controller.signal('somethingHappened', [
  syncAction
].concat(otherActions));
```

**Comment by idream3** [comment]
If we implement an array notation for the signals as I saw at one point you @christianalfoni were tossing about then we can just concat ourselves rather than adding more API.

```javascript
const $actionGroup = [
  action1,
  action2,
  [action3]
];

controller.signal('somethingHappened', [ someAction, anotherAction ].concat($actionGroup));
```

**Comment by christianalfoni** [comment]
Haha, that is just brilliant :D

**Comment by christianalfoni** [comment]
I will keep this open until it is documented ;-)

**Comment by christianalfoni** [comment]
that reminds me that we should support having an array at "top level" too. So:

```js
controller.signal('somethingHappened', someAction, anotherAction);
// is the same as
controller.signal('somethingHappened', [ someAction, anotherAction ]);
```

**Comment by idream3** [comment]
Another feature ticket perhaps  :)

**Comment by christianalfoni** [comment]
Changed this issue instead... though, hm, I think we have to require the top level to be an array. Because:

```js
controller.signal('somethingHappened', [asyncAction]);
controller.signal('somethingHappened', [syncAction].concat(otherActions));
```
They are not compatible... so yeah, that will break the API. But again, a quick fix and easy to throw error on it.

**Comment by idream3** [comment]
I see what you mean. Hmm, could start to look messy. I wonder if other people have suggestions...

**Comment by christianalfoni** [comment]
Yeah, lets keep it open and away more feedback. But signals are most commonly typed like this:

```js
controller.signal('somethingHappened', [ 
  [asyncAction] 
]);
controller.signal('somethingHappened', [
  syncAction
].concat(otherActions));
```
So it is not that bad ;-)

**Comment by idream3** [comment]
Ahh yes, the new line provides the visual separation :)

**Comment by garth** [comment]
If top level actions must be provided as an array then why not accept multiple arrays without the need for `concat()`?

```js
controller.signal('somethingHappened', [ 
  [asyncAction] 
], otherActionsArray);

controller.signal('somethingHappened', [
  syncAction
], otherActionsArray);
```

Just need to enforce that all arguments must be arrays.

**Comment by christianalfoni** [comment]
Jup, that I was also thinking about that. In that scenario it makes sense just to add it as a second argument, but:

```js
controller.signal('somethingHappened', [ 
  [asyncAction, {
    [SUCCESS]: [mySpecialAction].concat(otherSuccessActions)
  }]
], otherActionsArray);
```
So yeah, lets change to multiple arrays instead of multiple functions as arguments to the signal?

**Comment by idream3** [comment]
Can we use the ES6 spread operator for this perhaps?

```javascript
const otherActions = [
   action,
  otherAction
];

controller.signal('somethingHappened', [firstAction, ...otherActions] );
```
Example above:
```javascript
controller.signal('somethingHappened', [ 
  [asyncAction, {
    [SUCCESS]: [mySpecialAction, ...otherSuccessActions]
  }],
...otherActionsArray ]);
```

Second example: http://odetocode.com/blogs/scott/archive/2014/09/02/features-of-es6-part-5-the-spread.aspx

**Comment by christianalfoni** [comment]
Of course we can, haha, I have not got this new syntax into my intuition system yet ;-)

So we do not need to level at all, you can use spread for arguments too

```js
controller.signal('somethingHappened', controller.signal('somethingHappened', 
  firstAction, 
  ...otherActions
);
```
Let me update the other issue with this, and close this one. #46
