### ISSUE TITLE
Controlling flow of exceptions

### ISSUE THREAD

**Issue by a-s-o** [christianalfoni/cerebral#45]
Hello Christian,

I have just started using cerebral and I am trying to implement type validation on action inputs and outputs. I am running into some issues with the flow of errors. I am using a helper method `t.action` (see http://gist.github.com/a-s-o/e35edddf8d61c63e88d9) to create the actions as follows:

```javascript
   const resolveRoute = t.action({
      inputs: {
         route: t.Str
      },
      resolves: {
         pageTitle: t.Str
      },
      rejects: {
         error: t.Str
      },
      fn: function resolveRoute (args, state, promise) {
         promise.resolve({
            pageTitle: 3      // Let's introduce an bug here; instead of
                              // resolving with a page title string, we will
                              // resolve with a number which gets caught
                              // by the type system
         });
      }
   });

   const setTitle = t.action({
      inputs: {
         pageTitle: t.Str
      },
      fn: function setTitle (args, state) {
         state.set('pageTitle', t.Str(args.pageTitle));
      }
   });

   const displayError = t.action({
      inputs: {
         error: t.Str
      },
      fn: function displayError (args, state) {
         console.log(args);
         state.set('error', args.error);
      }
   });
```
The signal is defined as follows:

```javascript
   cerebral.signal('routeChanged', [resolveRoute, {
      resolve: [setTitle],
      reject: [displayError]
   }]);
```
As a result of the bug in in the `resolveRoute` action, I get the following errors in the console:
```javascript
[resolveRoute:resolves] /pageTitle is 3 should be a Str
[setTitle:inputs] /pageTitle is 3 should be a Str
[displayError:inputs] /error is undefined should be a Str
```
This is great and exactly what I expect but if instead of console.logging the errors from the validator, I `throw` the validation errors, the only error that gets caught is:
```javascript
Uncaught (in promise) TypeError: [displayError:inputs] /error is undefined should be a Str
```

##### My question is whether there is a way to get access to exceptions those exceptions that occur along the way in action handlers?

I suspect this has to do with the way thrown exceptions work in promises but I would expect to see the original `[resolveRoute:resolves] /pageTitle is 3 should be a Str`. Not having the original error is causing some grief finding where the error started in long chains.

**Comment by christianalfoni** [comment]
Hi there!

This is really interesting stuff :-)

Currently promises are used to resolve async actions and run actions in parallel, but you only have access to resolving and rejecting the promise, not the promise itself. 

But just to understand here. These type errors, you throw at line 5? It is not the fact that your validator stops running when you throw? Maybe you should do something like this instead?: 

```js
function checkValue (msg, value, type) {
	const check = t.validate(value, type);
	if (!check.isValid()) {
         try {
           throw new Error(...);
          } catch (e) {
            // Get stack trace and do your magic here?
         } 

	}
	return value;
}
```

**Comment by a-s-o** [comment]
Just to further clarify, let's say we alter the above actions and move the source of the error from the resolveRoute action to the setTitle action as follows:
```javascript
   const resolveRoute = t.action({
      inputs: {
         route: t.Str
      },
      resolves: {
         pageTitle: t.Str
      },
      rejects: {
         error: t.Str
      },
      fn: function resolveRoute (args, state, promise) {
         promise.resolve({
            pageTitle:  _.capitalize(args.route)   // No more error here
                                                   //  (pageTitle is now string) 
         });
      }
   });

   const setTitle = t.action({
      inputs: {
         pageTitle: t.Num // Error is now down here 
                          // bad input type of number
      },
      fn: function setTitle (args, state) {
         state.set('pageTitle', t.Str(args.pageTitle));
      }
   });
```
So in this case if I throw errors, I still get the same
```
Uncaught (in promise) TypeError: [displayError:inputs] /error is undefined should be a Str
```
instead of the more useful:
```
[setTitle:inputs] /pageTitle is "Some Route" should be a Num
```

Additionally, if the solution should be to rely on logging and not throw TypeErrors, can you please indicate what the best way would be to terminate the remaining actions. I have read a couple of the other issues on this topic (#43, #29) and it appears this is still being developed, so would like to know what your recommendation is currently. 

Thanks, appreciate the good work. Your videos are also very helpful.

**Comment by christianalfoni** [comment]
Or are you maybe throwing to actually make the chain stop? :-)

**Comment by a-s-o** [comment]
Yes, I would ideally like to throw and make the chain stop. Is that possible?

**Comment by christianalfoni** [comment]
Aha, I understand! And just to be perfectly clear, you want to throw multiple times to get a stack trace for each invalid arg/value? Or do you want to read something manually from the stack trace to put into the error? :-)

**Comment by a-s-o** [comment]
Well, the stack trace would be useful but the main goal is to get the origin of the error. If the error is that setTitle was passed a number instead of a string, I would like to throw at that point and then stop the rest of the chain. 

If the error is that resolveRoute's responsibility is to provide properties { x, y, z } but it only provides { x, y } then we throw at that point without even calling the next fn in the chain. The error message then helps us pinpoint the cause of the error

The idea is to make the actions declarative so that it is easier to re-use them in multiple signals, etc.

**Comment by christianalfoni** [comment]
Okay, cool, just a couple of more questions so I understand.

When you throw now, the chain does not stop?

What I can not quite get my head around is that in the first example you have three errors, but can only throw one.... but you can only throw one if you want the chain to stop when that happens?

Sorry that I am not getting it, but trying to build this in my head ;-)

**Comment by a-s-o** [comment]
Yup, I should have clarified that better. In the first example, as it is in the gist, I am NOT throwing the errors. I am simply logging using `console.error`. So the reason you see 3 errors is that as the chain was being executed, the validator simply validates and logs. In this case it ran into 3 errors and logged all 3.

However, if we change the validator from this:
```javascript
// Logging
function checkValue (msg, value, type) {
	const check = t.validate(value, type);
	if (!check.isValid()) {
		console.error(msg + ' ' + check.firstError().message);
	}
	return value;
}
```
to this:
```javascript
// Throwing
function checkValue (msg, value, type) {
	const check = t.validate(value, type);
	if (!check.isValid()) {
		throw new TypeError(msg + ' ' + check.firstError().message);      // Throws
	} else { 
	        return value;
        }
}
```

If we make the above change to THROWING the errors, then only this is reported:
```javascript
Uncaught (in promise) TypeError: [displayError:inputs] /error is undefined should be a Str
```
Sorry I wasn't clear about that before. Thanks for working through this

My guess is, the first throw will occur when resolveRoute:resolves is not provided a string. This error will cause the promise to be rejected, which triggers the displayError which is in the reject position.  This will cause the displayError:inputs to be evaluated and thus creating a new error there instead swallowing up the original error.

**Comment by christianalfoni** [comment]
Aha! So it is the wrong error.. I see. Now Cerebral handles a promise rejection as a "path", not an actual error, but this will change in the new version where we are going to implement `next(PATH, value)` where you never reject promises, only actual unwanted errors are rejections. These rejections will just be thrown like normal errors and stop the chain.

So yeah, I would suggest just logging for now and when next version is out you will safely be able to throw :-)

I will start working on the new version tomorrow. It is actually not such a big implementation, but quite a bit documentation and demos to update. So yeah, I think everything will be ready by the end of the weekend.

Seems okay?

**Comment by a-s-o** [comment]
Hi, found this. I believe the original error are being swallowed at this location https://github.com/christianalfoni/cerebral/blob/master/src/CreateSignalStore.js#L138-L143

**Comment by christianalfoni** [comment]
Okay, closing this as I brought this stuff together at: #46
