### ISSUE TITLE
Error from passing mouse event to signal has no stacktrace

### ISSUE THREAD

**Issue by saulshanabrook** [christianalfoni/cerebral#48]
When I pass a mouse event to a signal, I get an `Uncaught Error: You have to pass a serializeable object to a signal. Did you pass a mouse event maybe?(anonymous function) @ inserted-script.js:21` error.

However, it doesn't give any stacktrace, so it is hard to know what signal is being passed the incorrect object. It doesn't need a stacktrace, just some hints so it is easier to debug.

**Comment by christianalfoni** [comment]
Ah, yeah, hm... Cerebral should be able to output that :-) Let me check!

**Comment by christianalfoni** [comment]
Have started the work on "production vs dev" in Cerebral codebase. It will now try to serialize payloads to signals when running in dev mode, throwing error with signal name that caused the error.

**Comment by saulshanabrook** [comment]
Makes a lot of sense. How does one switch between dev and production?

**Comment by christianalfoni** [comment]
This depends on your setup @saulshanabrook. With webpack it is a matter of running the workflow with `NODE_ENV=production` or not. So yeah, it basically means `NODE_ENV=production`, which you should use when running any build scripts etc., it being webpack, browserify or whatever :)
