### ISSUE TITLE
Type Checking On Actions Fails on False Values

### ISSUE THREAD

**Issue by saulshanabrook** [christianalfoni/cerebral#49]
First off, thank you so much for the new type checker for actions. It really does work wonders for productivity. It seems like when I pass a false-y value in, it says I am giving the wrong input. By that I mean `""` or `0`, even when it is the right type.

**Comment by christianalfoni** [comment]
Hm hm, that is weird, as it checks the "typeof"... You do pas sit in as part of an object? Like: `output({myValue: false})`, not `output(false)`? I can have a looksy too

**Comment by christianalfoni** [comment]
Okay, this is fixed now, thanks for reporting :-)

**Comment by saulshanabrook** [comment]
Awesome :+1:
