### ISSUE TITLE
Throw errors on mutation methods in the async state object

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral#55]
You might be confused by the state object not having any mutation methods, so we could still have them, but throw errors instead.

The reason you can not mutate state there is because async actions are not run when remembering state. Only sync actions. But async actions outputs are remembered. This makes Cerebral able to replay signals synchronously, which is really important :-)

**Comment by dominicglenn** [comment]
I think documenting this in would be beneficial as I was unaware of the reason for not being able to mutate state during async methods myself.

**Comment by christianalfoni** [comment]
This now throws with error message indicating the problem, part of next release
