### ISSUE TITLE
Incorrect path passed to pop and shift hooks

### ISSUE THREAD

**Issue by gcanti** [christianalfoni/cerebral#59]
I think is due to this line:

https://github.com/christianalfoni/cerebral/blob/master/src/createActionArgs.js#L13

> // args can be (path, value), ([path], value), (value) 

It also can be `(path)` in case of pop / shift

Test case:

```js
var cerebral = require('cerebral');

var controller = cerebral.Controller({
  onPop: function (path) {
    console.log(path); // should output ['a', 'b'] but it outputs [] instead
  },
  onShift: function (path) {
    console.log(path); // should output ['c', 'd'] but it outputs [] instead
  }
});

controller.signal('test', function (input, state, output) {
  state.pop(['a', 'b']);
  state.shift(['c', 'd']);
});

controller.signals.test();
```

**Comment by christianalfoni** [comment]
Hi @gcanti ,

Aha, let me fix that and writes some tests. Working on new version now that will be released very soon :-)

Thanks for reporting!

**Comment by christianalfoni** [comment]
Okay, this is fixed with bunch of tests now. Will be part of next release

**Comment by gcanti** [comment]
Nice, thanks.
