### ISSUE TITLE
HOC alternative to the mixin

### ISSUE THREAD

**Issue by ksmth** [christianalfoni/cerebral#6]
Internally it could also reuse the mixin. It could look something like this:

```
function Cerebralize(Component, cerebralState) {
  return React.createClass({
    mixin : [ cerebralMixin ],
    displayName : `Cerebralized${Component.name}`,
    getCerebralState() {
      return cerebralState;
    },
    render() {
      return <Component signals={this.signals} {...this.props} {...this.state}>;
    }
  });
};
```
```
// ES5
var MyComponent = React.createClass({ ... });
MyComponent = Cerebralize(MyComponent, [ ... ]);
```
```
// ES6
class MyComponent extends React.Component { }
MyComponent = Cerebralize(MyComponent, [ ... ]);
```
```
// ES7
@Cerebralize([ ... ])
class MyComponent extends React.Component { }
```

**Comment by christianalfoni** [comment]
Thanks for the input, will make this part of next release! Change to props instead.

**Comment by christianalfoni** [comment]
This should be ready for next release, though I chose the name "decorator" on the file. so `import WhatEver from 'cerebral/decorator'. Will also activate decorators on the cerebral boilerplate by default. Still got `cerebral/mixin` available though. So the ES6 version uses the decorator version as that is likely to become the standard and the behaviour is the same.
