### ISSUE TITLE
Idea: splitting view and model related packages

### ISSUE THREAD

**Issue by gcanti** [christianalfoni/cerebral#60]
Hi @christianalfoni,

In order to understand how cerebral works I'm implementing a cerebral package backed by [tcomb](https://github.com/gcanti/tcomb):

[cerebral-tcomb](https://github.com/gcanti/cerebral-tcomb)

The goal would be to provide an immutable state which is also type checked.

Coming to this issue, all the `cerebral-react-*` packages share the same code for react. It would be nice to extract that code in a separate package. Something like:

- `cerebral-baobab`           (*model handler*)
- `cerebral-tcomb`            (*model handler*)
- `cerebral-immutable-store`  (*model handler*)
- `cerebral-react`            (**view handler**)
- `cerebral-react-native`     (**view handler**)
- ...

Then `cerebral-react-baobab` would be the mixin of `cerebral-react` + `cerebral-baobab`.

**Example**

```js
// cerebral-baobab package (just a model handler)

function controllerFactory(initialState, defaultArgs, options) {
  ....
}
module.exports = controllerFactory;
```

```js
// cerebral-react package (just a view handler)

function attachView(controllerFactory) {
  
  function factory(initialState, defaultArgs, options) {
    var controller = controllerFactory(initialState, defaultArgs, options);
    controller.injectInto = ...
    return controller;
  }

  factory.Mixin = ...

  factory.Decorator = ...

  factory.HOC = ...

  return factory;
}
```

and then

```js
// cerebral-react-baobab package
var controllerFactory = require('cerebral-baobab');
var attachView = require('cerebral-react');
module.exports = attachView(controllerFactory);
```

**Comment by christianalfoni** [comment]
I think this is a really great idea :-)

I have to review the code and stuff, but yeah, it makes total sense and we should do this! I am currently working on a new version, but will do this as soon as I can!

Thanks for great feedback!

**Comment by christianalfoni** [comment]
This is released!

**Comment by gcanti** [comment]
Great, thanks @christianalfoni
