### ISSUE TITLE
Question: how to handle a modal

### ISSUE THREAD

**Issue by a-s-o** [christianalfoni/cerebral#62]
Hi Christian,

I have a question about modeling state for a stack of modals and what the best way would be to separate actions and signals. Here are the details.

First, let me just explain the `modal` service which I call as follows 
```javascript
var instance = modal(Component, ...componentArgs)
// instance.open() returns a promise
instance.open().then(modalClosedOnSave).catch(modalDismissed)
```
When `instance.open()` is called, the modal is pushed onto a stack; when a backdrop is clicked or user presses escape, etc. the top most modal is popped off the stack. On each event, my view layer simply renders the whole stack. This way, I am able to have nested modals. 

Ex. I have a form with some fields. Some of the fields then can be clicked to open a selector modal which has a long list of options for them to select. When they select an option, the selector modal gets closed but the form modal underneath remains open and the field gets filled in with the option. 

So, unlike dropdown menu state, or input focus state, which is limited to just one component, the state of the modal stack is globally relevant so I would like to store it in baobab. 

My question is how should I handle this state with cerebral actions and signals. Here is the full flow:

1. User is on documents page. They can click a button to open the modal which contains the `add-document` form component. Stack consists of `[add-document]`
2. The user can start filling out the form. They get to a project field where they can assign the document to a project. They click a button which opens another modal responsible for loading projects. They can type a few letters to search for the project by name and the projects are then loaded. Modal stack at this point consists of `[add-document, project-selector]`
3. They select a project and the top modal closes. Selector closes and updated stack consists of `[add-document]`
4. They want to finish the form later so they dismiss the add-document modal. Stack `[ ]`; all modals closed but the form state is saved

### What would be a good separation of the above flow into signals?
Here is my attempt
```javascript
cerebral.signal('addDocumentClicked', [openModal, {
  resolved: [saveAddDocumentForm, submitAddDocument, {
     success: [clearAddDocumentForm],
     error: [showNotification]
  }],
  dismissed: [saveAddDocumentForm]
}])
```

### What mutations should be made to state in `openModal`? 
Remember, the modal service requires a component. So is it okay to pass a component as `args` to an action? Finally, the modal stack stores a dynamic instance of the component and not a serializable object so how should the state be stored in baobab, for example?

Sorry for the long question, but I am just trying to wrap my head around this. I also think this is sufficiently complex example that people will run into when using cerebral, so I would like to understand the best practice so we can hopefully turn it into an article or tutorial for the cerebral wiki.

**Comment by christianalfoni** [comment]
I am about to leave the office here, but just wanted to write down what I generally think about this situation. Maybe it helps, if not, I will read through everything and we can discuss a solution :-)

There are many APIs that does not support a state driven/declarative applications and modals/dropdowns are the worst!

Why have:

```js
myDropdown.open()
```
When you can:
```js
<myDropdown open={this.state.isOpen}/>
```
With the second example you can control the dropdown completely from your application state, but the first example requires extra logic that is fragile.

So handling multiple modals on top of each other should, in my opinion, be done using an array:

```js
const state = {
  modals: []
};
```
When you want to display a new modal you push an object to modals:

```js
state.push('modals', {
  title: 'someTitle',
  props: someData,
  component: 'UserForm'
});
```

Then you have a component using this "modals" array and just renders modals like if it was a normal list. When you close a modal you just `pop()` one off the list and the "modals component" will not render one less. To make it fade etc. you have to use the same technique as transitioning list items in a normal list.

It is really too bad that most modals/dropdowns are "imperative", calling them to change state, and not "declerative"... just change a property.

But yeah, I hope this made some sense :-)

**Comment by christianalfoni** [comment]
I had some extra time, so I see my comment did not make complete sense, hehe... but I will leave it. Okay, this is a different approach where the modal component does not control anything. Everything is controlled by Cerebral:

Something like this:
```js
cerebral.signal('addDocumentClicked', openModal);

cerebral.signal('addDocumentSaveClicked', 
  [
    saveAddDocumentForm,
    submitAddDocument, {
     success: [clearAddDocumentForm, closeModal],
     error: [showNotification]
    }
  ]
);

cerebral.signal('addDocumentAbortClicked', 
  [
    saveAddDocumentForm
  ], 
  closeModal
);
```

**Comment by a-s-o** [comment]
Wow, thanks for taking a look at that. No rush, by the way, this can wait until it is convenient for you.

You're right I am also not a fan of modals as a promise but in some cases they just work so well. For example, in the `project-selector` modal's case, the modal just behaves like a normal `select` form control but instead of dropdown it is a modal. I can use this control over and over in different forms which need a project selection. 

So, having separate `addProjectsClicked` and `projectsSelectClicked` does not fit as well, since I will need to have signals for each form where the selector is used. Basically, the modal needs to callback the original form with the selection value or notify it on dismissal.

Finally, in terms of the modal stack, you are recommending, passing in an identifier string `UserForm` which can then be rendered declaratively. That seems okay, but, I guess the modal service will need to then maintain a map of all the possible modals, instead of just receiving a Component in the constructor.

**Comment by a-s-o** [comment]
Okay, I think I understand what you said about using the declarative style modal component. I should just have flags for all of the places that are calling modal.open() and if the flag happens to be true open the modal. I will try and implement that. If it works out, I will turn it into a short tutorial of sorts.

Closing the issue for now. Thanks.

**Comment by christianalfoni** [comment]
Cool! Yeah, let me know if you want to discuss it more. This is an interesting topic :-)

**Comment by a-s-o** [comment]
Hello @christianalfoni.

As promised, I wrote down a short tutorial on how to handle modal state declaratively based on your input and also how to integrate the state with cerebral. I have added it to the wiki [How to store modal state](https://github.com/christianalfoni/cerebral/wiki/Tutorial:-How-to-store-modal-state).

Please have a look and feel free to change in necessary. Thanks

**Comment by christianalfoni** [comment]
Awesome! Thanks for the writeup! I am working on a new webpage now where I will take inspiration from this! :)
