### ISSUE TITLE
What's the correct signature of the onMerge and onUnset hooks?

### ISSUE THREAD

**Issue by gcanti** [christianalfoni/cerebral#64]
Hi Christian,

after upgrading to v0.15 two tests of cerebral-tcomb that used to work now fail:

**1.**

in this example https://github.com/christianalfoni/cerebral#arguments `merge` seems to accept a string or a path (i.e. a list of strings) but now it seems to accept only a path due to:

https://github.com/christianalfoni/cerebral/blob/master/src/createActionArgs.js#L36

is it by design or a bug?

**2.**

in the https://github.com/christianalfoni/cerebral#how-to-create-a-custom-cerebral-package code snippet
the signature of `onUnset(path, key)` is the only API which has also a `key` argument and now it seems to handle only the `path` argument

is it correct?

EDIT:

After other tests the result is:

These work:

```js
state.unset('field1');
state.unset('field1', 'field2');
state.unset(['field1', 'field2']);
```

This doesn't work:

```js
state.unset(['field1'], 'field2');
```

Hope these reports are helpful.

Giulio

**Comment by christianalfoni** [comment]
Hi @gcanti,

In the latest version of Cerebral there are only two signatures for paths:

```js
state.unset('foo')
state.unset(['foo', 'bar']);
```
Only the `get()` method is allowed to have multiple strings as path:

```js
state.get('foo', 'bar', 'hey');
```
Because that method will never have a value.

So the mutation methods all trigger the same way now :-)

**Comment by gcanti** [comment]
Thanks, I'll upgrade to v0.16 asap
