### ISSUE TITLE
Numbered errors

### ISSUE THREAD

**Issue by a-s-o** [christianalfoni/cerebral#65]
Hello,

I started a wiki page (https://github.com/christianalfoni/cerebral/wiki/Errors) for the errors I was running into which were not immediately clear to me. Please have a look. 

I can continue to document other errors I run into but I wanted to ask what you think of adding some numbering to the error messages that are thrown? It would make it easier to document the reasons and fixes for different errors.

**Comment by christianalfoni** [comment]
Yeah, that is a really good idea. Let me take a look at the errors you got an I will give them numbers and document them. Just got a pull request from @idream3 also fixing some error stuff.

**Comment by idream3** [comment]
My fix is for the first Error in @a-s-o 's list.

It produces an error description saying the index of the action and that it doesn't exist: https://github.com/christianalfoni/cerebral/pull/67

I have not tested across paths or async so it is likely that this message can be improved upon :)

**Comment by christianalfoni** [comment]
Lets me add the error fixes to the next release list :-)

**Comment by christianalfoni** [comment]
actionFunc error is fixed now, closing this
