### ISSUE TITLE
Signal end event

### ISSUE THREAD

**Issue by markuplab** [christianalfoni/cerebral#66]
Hello @christianalfoni! I have some troubles when use cerebral on server-side.
I need wait when signal actions end, and then run rendering. But i can't subscribe on any event, i can only analyze how many updates will be triggered durning signal run.

Do you can add special event for signal end?

**Comment by christianalfoni** [comment]
Hi there!

I am doing some changes in the new version. You will be able to listen directly on Cerebrals "change" event. This is triggered whenever a render would be required to keep in sync with state :-)

I hope to release it tonight!

**Comment by markuplab** [comment]
Hi, in 0.16.0 i still can't catch when end signal run.

```
if (executionArray.length) {
...
} else if (!signalStore.isRemembering() && !recorder.isCatchingUp()) {
  controller.emit('end');
  ...
}
```

**Comment by christianalfoni** [comment]
Hi again!

Hm, maybe I misunderstood what you wanted it for. You only want to know when signal is done? Or do you need to know when to render?

Now the controller triggers a `change` event whenever there is need to render in the VIEW layer. Maybe you could describe a bit more about your scenario. There is no problem to implement "signal end" event, I just have to understand why :-)

**Comment by markuplab** [comment]
Yes, i want know when signal done, because on server (isomorphic render) i run only one signal that handle current route. I want start render when signal done, and all data already in tree.

**Comment by markuplab** [comment]
Change is useful for client-side, when you can rerender on each "change", but on server we don't rerender, we just "render" one time and send html to user :)

**Comment by christianalfoni** [comment]
Aha, now I see @markuplab :-)

My initial thought was that signals should not need to run on the server, but again... just an initial thought. I have been playing around a lot with isomorphic apps, but have not gotten to that part with Cerebral yet. So I am really happy that you are trying this out!

So let me implement the event and release a new version today.

**Comment by markuplab** [comment]
Now we work with Catberry-Cerebral-Baobab stack. On server we run only one signal, and render simple html string by handlebars, on client-side we sub on Baobab.watchers, and on each update we morph DOM nodes (https://github.com/patrick-steele-idem/morphdom). It's work very fine and fast. We have only one hard work, restore initial state at client-side. We need cache our async requests, and when app start on client-side, we run same signal that was run on server, and use cache when async action execute. 

Thanks, for help.
https://github.com/catberry/catberry - You can also experiment on isomorphic cerebral apps.

**Comment by grigio** [comment]
Maybe is related, but how can be updated the state without a user action? (example a list of chat messages)

**Comment by christianalfoni** [comment]
@grigio You can trigger a signal from anywhere really. You just have to point to the controller you have created: `controller.signals.messageFromWebsocketReceived({message: message})` ... as a silly example :-)

@markuplab Sorry about delay on the event, have a couple of other things I want to bring into the release
