### ISSUE TITLE
Separate input and injected utilities

### ISSUE THREAD

**Issue by bfitch** [christianalfoni/cerebral#69]
Inspired by http://elm-lang.org/guide/reactivity and these tweets: https://twitter.com/dan_abramov/status/633320496357093376. Would be interesting to explore the value of separating "services" (http, localstorage, websockets, etc) from regular action input.

@christianalfoni noted (in Gitter chat) that the action signature `(input, state, services, output)` poses no implementation challenges.

Is there value in "services" as a first class concept in Cerebral?

**Comment by dominicglenn** [comment]
My question would be, not so much the difference between having them on the `input` vs `services` but more about, why would you put them on either of those in the first place, as opposed to just `import MyService from './myservice'` or something.

I'm wandering what the distinction there is, or specifically the use case. The temptation might be to end up with a huge `services` with everything under the sun?

**Comment by bfitch** [comment]
@dominicglenn good point. There's already the idea of passing utility libraries like ajax into `inputs` via `defaultInput = {utils: {request: ajaxLib} }`, so my thinking was that services would expand that idea.

**Comment by christianalfoni** [comment]
There is one single reason for this... testing :-) Having pure functions is a really great concept. It will make it incredibly easy to test all your actions as they only operate on arguments passed to them.

It also creates less dependencies in your app, making it easier to reason about. Instead of each action depending specifically on a module,  you can head into your `controller.js` file and see what is exposed to all your actions.

**Comment by dominicglenn** [comment]
So dependency injection then I guess? The only thing is, with reasonably sized projects it would not be clear, by looking at the top of an action, what services it requires to function, without reading the source code. In this scenario you would potentially have to build an entire mock controller, with all services mocked, to test a single action that maybe only uses one service.

I am mentally comparing these services to the dependency injection provided by angular for example. Is there a more elegant solution we could have to injecting only those services that an action depends on, and not the entire blob?

**Comment by bfitch** [comment]
Wouldn't this make it more clear, though? You could pass in mocked services and see what the dependencies are:
```js
function myAction(input, state, services, output) {
  services.socket.listen(function(data){
    output.success({data: data});
  });
}
```
I don't quite see how you'd need a whole mock controller, as each action under test would just need to mock its services, like the websocket above

I think the situation already applies with ajax utilities, right? You need to mock `input.utils.ajaxLib`. But, perhaps I'm missing something?

**Comment by christianalfoni** [comment]
Hm, yeah, I am a bit unsure what you mean by mocking the whole service for each action @dominicglenn. You only mock methods the action specifically uses. You just want to make sure that the action handles the input, calls the methods you expect and creates the output expected.

So a test would be:

Action
```js
function myAction (input, state, output) {
  input.utils.ajax(input.url).then(function (result) {
    output(result.user);
  }); 
};
```
Test
```js
var myAction = require('./actions/myAction.js');
exports['should call ajax lib with url and pass result as output'] = function (test) {

  var fakeAjax = function (url) {
    test.equal(url, '/user');
  };
  fakeAjax.then = function (cb) {
    cb({user: {name: 'john'}});
  };
  var input = {
    url: '/user',
    utils: {ajax: fakeAjax}
  };
  var output = function (user) {
    test.deepEqual(user, {name: 'john'});
  };
  test.expect(2);
  myAction(input, {}, output);
  test.done();
};
```

You could of course very easily create a factory producing these fake Ajax stuff, or if there is a mock version of the lib your are using. But yeah, this is the idea :-)

**Comment by dominicglenn** [comment]
I was kind of being obtuse; I'm a fan of the way that Angular does their DI (in some respects), where it is easy to tell, by looking at the top of the action/service/whatever which services it depends on.

Using a services parameter would be the best option, and make an important distinction, also you could so something like the following:
```
function myAction(input, state, {myService}, output){
  //dosomething
}
```

Which in my opinion would be awesome, and makes it immediately obvious which services it depends on, as long as you don't mind using new features.

**Comment by christianalfoni** [comment]
This is great stuff @dominicglenn, creating a new feature issue now :-)

**Comment by christianalfoni** [comment]
This is in now

**Comment by tnrich** [comment]
Hey @christianalfoni , I still don't quite understand why it would be bad to have, 

```
var lodash = require('lodash');
```

at the top of an action file and subsequently used in the action?

How does that make it less modular/testable? This seems like classic commonjs to me..

**Comment by christianalfoni** [comment]
@tnrich With lodash it it does not matter too much, but replace that with:

```js
var request = require('superagent');
```
Now you have an ajax lib. You do not want to fire of ajax requests testing your action, but you want to verify that it uses an input for the url etc. By passing `superagent` on the services you can mock services when testing.

Pure functions is a really great concept and we should strive for it, it makes the functions and the module defining them less dependent on other parts of your app. It is a good thing :-)
