### ISSUE TITLE
More explicit names

### ISSUE THREAD

**Issue by ksmth** [christianalfoni/cerebral#7]
I don't know whether this is bike shedding or not, but here I go. 😉 I know this is really a matter of taste and I tend to use long names for everything, but I think it makes everything clearer and with code completion and snippets I think long names are a none issue. I was reading through the [introductory blog post](http://www.christianalfoni.com/articles/2015_05_18_Cerebral-developer-preview) and noticed a few things:
```
let projectRows = function () {
  return {
    // if this value is changing, it should be obvious by the name, as with React components
    initialValue: [],
    
    // I'm torn on this one. it should be the same for both the mixin and here, so if it's
    // `getCerebralState` in the mixin, it I think should also be `state` here or `dependencies`
    // and then also `getCerebralDependencies`. Or maybe `dependsOn`? In any case I really don't
    // shortened words, as the way people shorten things differs from project to project and you (well, I)
    // never get it right.
    dependsOn: ['projects'],
    get(cerebral, states, ids) {
      return ids.map(id => states.projects[id]);
    }
  };
};
```
Dependencies is a really long word, but it describes it very well ... hmm, maybe there is an alternative lurking somewhere? But the more I think about it, I think it should be state everywhere.

**Comment by christianalfoni** [comment]
Hi @ksmth ,

Thanks for great input, will definitely change to "initialValue". 

I think depends might be the wrong word, because it does not really depend on it, it more "relates" to it. So if it changes the state will update. Maybe "linkState"... hm, does this inspire more suggestions on your end? :-)

**Comment by ksmth** [comment]
`composedOf`, `basedOn`, `buildsUpon`, 'reliesOn', `sourcedBy`, `connectedTo`, `linkedStates`, `relatedStates`, `sourcedStates`, `consumedStates`, `connectedStates` ... hmmmm

**Comment by christianalfoni** [comment]
What about "sources"? I did quickly lean towards talking about "source data" used with lookups, and that is basically what you want to do.

let projectRows = function () {
  return {
    initialValue: [],
    sources: ['projects'],
    get(cerebral, sources, ids) {
      return ids.map(id => sources.projects[id]);
    }
  };
};

?

**Comment by RJ** [comment]
`initialValue` and `sources` seem good to me. I think it's useful that whatever word used there can be mirrored in the parameter name used in the `get()` function.

both `sources` and `deps` make suitable parameter names, something like `dependsOn` wouldn't. Using the same name in close proximity in the code reinforces what's going on imo.

ie: this looks gramatically weird to me

    dependsOn: [...],
    get(cerebral, dependsOn, ids) { ...


but this looks fine:

    sources: [...],
    get(cerebral, sources, ids) { ...

**Comment by ksmth** [comment]
@RJ yes, you're absolutely right. what I'm still missing from `sources` though is the `state`, I think. it's states you're referring to right there and it should be as obvious as possible without being annoying. As said before, I have a high tolerance for verbosity, but my preferred version would be `sourceStates`.

**Comment by christianalfoni** [comment]
What about: 

```js
let projectRows = function () {
  return {
    initialValue: [],
    sourceValues: ['projects'],
    get(cerebral, sourceValues, initialValue) {
      return initialValue.map(id => sourceValues.projects[id]);
    }
  };
};
```
Or
```js
let projectRows = function () {
  return {
    initialState: [],
    sourceStates: ['projects'],
    get(cerebral, sourceStates, initialState) {
      return initialState.map(id => sourceStates.projects[id]);
    }
  };
};
```

**Comment by RJ** [comment]
i like sourceStates

**Comment by christianalfoni** [comment]
Well.. hm, it would actually have to be `sourcesState` to be correct. Multiple sources with one state each. Makes sense?

**Comment by christianalfoni** [comment]
or, hm, could say we create a sourceState.. yes... sorry, sourceState it is :-)

**Comment by RJ** [comment]
:+1:

**Comment by christianalfoni** [comment]
Okay, so the theory is:

**initialState**: The state the path starts with
**sourceState**: A state representing a source for lookups
**get**: You know...

I will put one last suggestion out there though, instead of `sourceState`, `lookupState`. It is a state for doing lookups.

**Comment by christianalfoni** [comment]
You know what, I like `lookupState`. It just says exactly what it is. Will leave it until release, which will be tomorrow.

**Comment by idream3** [comment]
Adding one more suggestion - mix & with.

initialState
mixState
with

**Comment by christianalfoni** [comment]
Thanks for all input, just recorded some videos with the new "lookupState" name. So it stays for now :-)
