### ISSUE TITLE
Imporvement: Output paths can be called without arguments

### ISSUE THREAD

**Issue by idream3** [christianalfoni/cerebral#70]
Relates to Errror: https://github.com/christianalfoni/cerebral/wiki/Errors#output-path-was-called-without-arguments

This has also tripped me up and I don't see any reason to make it mandatory to pass an argument to an output. Some times you just want to go down a path and use the existing properties on the input chain.

I also think that `ouputs` signature for emtpy/null arguments should be:

```javascript
checkStaffList.outputs = {
   stale: null,
   fresh: null,
   fetching: null
};
```

**Comment by christianalfoni** [comment]
Hi @idream3,

Yeah, you make a good point here. But maybe it should be `undefined` as that is really what you are passing when you do not pass anything, heh.

Hm hm...

```js
checkStaffList.outputs = {
   stale: undefined,
   fresh: undefined,
   fetching: undefined
};
```

**Comment by christianalfoni** [comment]
No biggie, but yeah, I think it says more about what you want that output to do

**Comment by idream3** [comment]
Sure, but can we make it `null` or `undefined` and leave it up to the developer? you don't have to document it :)

**Comment by christianalfoni** [comment]
This is part of latest release :-)
