### ISSUE TITLE
Abort a signal without 'change' event emitting

### ISSUE THREAD

**Issue by idream3** [christianalfoni/cerebral#71]
I have ran into the situation where I want to abort a signal and not trigger updates in the view.

Eaxmple

```javascript
function getCurrentPosition(input, state, output) {
  let node = state.get('selectedNode');

  if (node) {
    if (node.$isLeaf) {
       output.onNode({
        index: node.$index,
        node: node
      })
    }

    if (node.$open) {
       output.onOpenNode({
        index: node.$index,
        open: false,
        node: node
      })
    }
  }

  // no node is selected so I don't want this signal to trigger a change event. 
  // Currently I need to create a path that goes nowhere because you cannot not output a path.
  output.onRoot([]);

  // ideally I would like to
  output.abort();
}
```

**Comment by christianalfoni** [comment]
Hi @idream3,

It is really important that Cerebral triggers general changes as you will quickly get into bugs if you start manually syncing this stuff. But why does your UI display the wrong thing when an update occurs? The UI should be a reflection of current state, so if no state changes are done, it should display the same?

Or do you just want to optimize? :-)

**Comment by idream3** [comment]
Hey @christianalfoni 

It is only for optimizing :)

It means I can put more logic in actions/signaIs rather than the view if I know a path is going to have a dead end. For example, take keyboard input. The `left` key will only have an effect if an item is selected, or else it will do nothing. The view can either hold this logic and then send more specific signal or I can send a generic `keyPressed` signal which I prefer.

Currently I have to have an empty function to route a signal path through if there is no intended action. Because currently you can't return undefined from an action that has `outputs`. But when I do that it also triggers a `change` event and a bunch of unecessary logic happens with the view layer in terms of checking if it should update.

Consider:

```javascript
Controller.signal('keyPressed',
  getKeyPressed, {
    left: [determineAction, {
      allow: [doAction],
      disallow: [noop]
    }]
  }
)
```

What I think would be better is:

```javascript
Controller.signal('keyPressed',
  getKeyPressed, {
    left: [determineAction, {
      allow: [doAction]
    }]
  }
)

function determineAction(input, state, output) {
  if (condition) {
    return output.allow({ ... });
  }

 output.abort();
 // or
 output.cancel();
}
```

Unless you can see another way to do this or have other ideas?

**Comment by christianalfoni** [comment]
Aha, I see your point :-)

I am holding back a bit on allowing to manipulate how the signal runs, when it runs, until we get more experience. Like, "is it really necessary to have that optimization?" or "can we solve things differently?". And in this case it is not really a matter of optimization I think, but principle. Do not run code that is not necessary, but you could say that about React too :-) It runs A LOT of code that is not strictly necessary, but it does it to ensure consistency. Which I think signals also should do. And it does not affect the user experience.

So again, I see your point, but I favour consistency over principle here... if that makes sense :-)

And if you worry about running signals too often, you can filter out calls in the component that triggers the signal... as you stated. So yeah, it just adds complexity to the API and internals of Cerebral. "The winning goes up in the spinning" as we say here in Norway ;-)

**Comment by christianalfoni** [comment]
Just closing this for now, please reopen if you want to discuss it more :)
