### ISSUE TITLE
Syntax change: outputs => output

### ISSUE THREAD

**Issue by idream3** [christianalfoni/cerebral#72]
Opening this ticket to have a discussion.

I think we should keep the syntax consistent and just use `input` and `output`, regardless if there are multiple outputs/inputs.

```javascript
someAction.input = {
   input1: Object,
};

someAction.output = {
   path1: {},
};

someAction.output = {
   path1: {},
   path2: null,
};
```

Either that or make the error message more descriptive about the differences between `output` and `outputs`.

p.s. see this ticket for explanation of the `null` value: https://github.com/christianalfoni/cerebral/issues/70

**Comment by christianalfoni** [comment]
hi @idream3 ,

I am always up for having less stuff to think about. Though I can not quite see how you would be able to type check an aciton that does not have any paths?

```js
// output({foo: 'bar});
someAction.output = {
  foo: String
};
// output.foo({bar: 'bapbop});
someAction.outputs = {
  foo: {
    bar: String
  }
};
```

**Comment by idream3** [comment]
Can you not do something like this?

```javascript
Object.keys(action.output).forEach((key, i, obj) => {
  function checkType(type) {
    if (isObject(type)) {
       // object, so treat as an output path and
       // iterate keys to get arg types
      Object.keys(type).forEach((key, i, obj) => {
        checkType(obj[key]);
      });
    } else {
      // ... check `type`
    }
   }

   checkType(obj[key]);
});
```

**Comment by christianalfoni** [comment]
I think you have to recruit some people who shares your opinion ;-) I am not totally against it at all, but it hides the implementation details more... which in this case I do not think is better.

Lets look at the errors at least!

**Comment by christianalfoni** [comment]
Just closing this to clean up issues, please reopen if you want to discuss more!
