### ISSUE TITLE
Synchronously update state from actions

### ISSUE THREAD

**Issue by a-s-o** [christianalfoni/cerebral#73]
Hey, Christian. This is a continuation of discussion in https://github.com/gcanti/cerebral-tcomb/issues/1 and I think the rest of my question fits better here.  

I was working on implementing loaders in my cache store and I am running into an issue. I wrapped the model's `.get()` as described by Giulio above to make loaders run when a value is not found at certain state paths. Currently the logic is as follows (pseudo code):
```javascript
model.get = _.wrap(model.get, function wrapped (next, path) {
    // Check if value exists
    const value = next(path);
    if (value) return value;

    // Check if loader found
    if (loader) {
       const inputs = { path: path, lookup: [/* path after the loader position */] }
       const placeholder = loader(inputs, model);
       return placeholder;
    }

    return undefined;
});
```
This is what my example loader code looks like
```javascript
   function loadStaff (input, model) {
      // Call the signal responsible for fetching
      input.utils.signals.staffRequested({ id: input.lookup[0] });
     
     // Make a placeholder; I am doing this in the signal as well but it
     // needs to be duplicated due to async state updates
      const placeholder = {
         _id: input.lookup[0],
         _isFetching: true
      };
   
      // Manually update state for any re-gets before the signal 
      // updates are flushed
      model.mutators.merge(input.path, placeholder);
   
      // Return the placeholder as response to the original get call
      return placeholder;
   }
```
As you can see, I am manually returning a placeholder from the loader. This will be used for the response on the original `get` call, form a component, for example. The problem is that at the same time, I also have to synchronously merge the placeholder manually into the state store. 

I can't do it in the signal, since it will run at next frame. If I don't update state synchronously, then if the component re-renders before signal completes or another component requests the same path, it will re-run the loader. This way cerebral is also not aware of the state mutations.

So my question is, is there a way for some signals/actions to synchronously update state, because that way, it may be possible to simply define loaders as:
```javascript
   function loadStaff (input) {
      input.utils.signals.staffRequested({ id: input.lookup[0] });
      // Placeholder is saved by the signal itself all future gets
      // should have get the placeholder until the request completes
   }
```
and then in get:
```javascript
    // Check if loader found
    if (loader) {
       loader(inputs);
       // Re-get the path which will get the placeholder
       return model.get(path);
    }
```

**Comment by a-s-o** [comment]
Wow, by the way, thanks for your article about the baobab loader pattern. I am just walking through my code remove all the places where all I was doing was fetching and caching individual documents or invalidating stale documents and now it is all in one function +  one signal

**Comment by christianalfoni** [comment]
Hi @a-s-o,

It is possible to trigger signals with: `controller.signals.appMounted(true, {})`, that will make it run synchronously. Would that work? Though automatically loading is a great feature, I am very unsure if it should be the job of the model layer in Cerebral. That is more the "database", where state is stored, not fetched from other sources.

An example of this is Falcor from Netflix. Even though they call it a model, the best way to implement it with Cerebral is to use it as a service. It is more of an ajax library with caching really, not a model layer.  The reason is that Falcor can not handle general state, only stuff from the server.

So yeah, I am not saying that I am disagreeing with your approach at all, just adding to the discussion :-) Let me know how it works out, and we can discuss more.

Thanks for the feedback on the article, glad it helped you out! :-)

**Comment by a-s-o** [comment]
Hi. Thanks for that tip. That was exactly what I need. You're right about the auto-loading; not so clean to separate it but it is for very specific cases where the logic basically boils down to (get value; if no value then fetch value). Such a simple task that just gets scattered all over the codebase; so in those cases, I am finding an auto-triggered signal is very useful.

Thanks again.
