### ISSUE TITLE
Hydrate/Dehydrate model layer

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral#80]
Sometimes you want to grab all the state from the model layer to store it in local-storage or on the server. Then put that state back in.

I suggest we add a couple of hooks, example with immutable-store

```js
return {
      get: function (path) {
        return pathToValue(path, state);
      },
      toJSON: function () {
        return state.toJS();
      },
      getInitialRecordingState: function () {
        return state.export();
      },
      hydrate: function (newState) {
       state.set(newState);
      },
      dehydrate: function () {
        return state.export();
      },
      mutators: {
        set: function (path, value) {
          var key = path.pop(); // You can safely mutate the path
          state = getValue(path, state).set(key, value);
        }
      }
    };
```
`getInitialRecordingState` is actually a bit overkill now, as it basically wants to dehydrate the state. So yeah, this are just internals so can easily create a new version with this stuff.

The difference between `toJSON()` and `dehydrate()` is that `toJSON()` shows the mapped values, but `dehydrate()` gives the mapping data. This is also relevant with Baobab and possibly other model layers.

So:

```js
controller.hydrate({foo: 'bar'});

controller.dehydrate(); // {foo: 'bar'}
```

**Comment by Guria** [comment]
:+1:

**Comment by christianalfoni** [comment]
Part of next release
