### ISSUE TITLE
Video suggestions

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral#81]
I think the best way to learn stuff is to watch videos, so I thought I would make a few shorter videos on different concepts with Cerebral. Here are some suggestions:

- Routing
- Functional concepts (composing actions, factories etc)
- ...

**Comment by Guria** [comment]
+1 for routing.

**Comment by bfitch** [comment]
:+1:  for composing actions and action factories

**Comment by christianalfoni** [comment]
Okay, I think these are covered for now :-)
