### ISSUE TITLE
How to test with Cerebral

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral#82]
Hi,

We started a discussion on testing with Cerebral. There are multiple approaches here and I think we need to explore a bit more before setting a "best convention".

Here are the approaches:

### Test the signals as they are defined in the app

```js
import controller from './path/to/cerebral/controller';
import './path/to/signal/to/test';

it('should run the signal', function (done) {
  const onEnd = function () {
    expect(...);
    done();
  };
  controller.once('signalEnd', onEnd);
  controller.signals.somethingHappend({...});
});
```

Now, this is more of an "E2E" test as you bring in a lot of your application into the test. It can not really be defined as a UNIT test. Also you will have a much harder time mocking out services etc. Tests will likely also leak into other tests as now they share the model layer.

### Only test actions

```js
import actionToTest from './path/to/action/to/test';

it('should do something', function (done) {
  const mockedInput = {};
  const mockedState = {};
  const mockedOutput = {};
  const mockedServices = {};
  
  actionToTest(mockedInput, mockedState, mockedOutput, mockedServices);
});
```
Now you have completely isolated tests and you can mock your brains out. You are also free to mock exactly what you need to test the specific action. 

### Summary
So my take on this is that you should not really test signals specifically. How they work will be tested through E2E tests, where you actually test interaction etc. By doing pure unit tests of each action you secure their functionality and they will break as soon as somebody changes any action, which is the point of UNIT tests. They avoid making changes without consideration.

But yeah, this is just my perspective :-)

**Comment by garth** [comment]
I agree that testing signals is like E2E, but it's nice to test all E2E logic without having to poke around in the HTML to check the results. With signal tests you can simply:

1. Set initial cerebral state
2. Send one or more signals
3. Check the final cerebral state

Sure the setup can be a little tedious, but with a couple of helper methods you end up with something that's pretty simple and can even run server and client logic in a single test process, so it's still reasonably quick.

Here's my current setup:

```js
// test/helpers/session.js
import app from '../../server'; // express app that exports app without calling listen
import controller from '../../client/controller';
import supertestSession from 'supertest-session';

const Session = supertestSession({ app });

export default function () {
  let session = new Session();
  // replace superagent with supertest, other services can be swapped out here also
  controller.services.request = session;
  return session;
}
```

```js
// test/helpers/signal.js
export default function (controller, signal, data, test) {
  return new Promise(function (resolve, reject) {
    controller.once('signalEnd', function () {
      if (typeof test === 'function') {
        try {
          test();
        } catch (e) {
          return reject(e);
        }
      }
      resolve();
    });
    signal(data);
  });
}
```

```js
// test/signaltest.js
import { expect } from 'chai';
import Fixtures from './fixtures';
import controller from '../client/controller';
import '../client/signals/signal-to-test';
import getSession from './helpers/session';
import testSignal from './helpers/signal';

describe('signal-to-test', function () {

  before(function () {
    this.fixtures = new Fixtures();
    this.session = getSession();
  });

  beforeEach(function (done) {
    this.fixtures.reset(done);
  });

  after(function (done) {
    this.session.destroy();
    this.fixtures.destroy(done);
  });

  it('should do stuff', function () {
    return testSignal(controller, controller.signals.signalToTest, {}, function () {
      expect(controller.get('someKey')).to.equal('expectedValue');
    });
  });

});
```

With this setup it's now possible to write system tests by simply calling a number of signals chained together via promises.

After the discussion yesterday I don't think that anything needs to change in cerebral to support signal or action testing. Though some documentation could be helpful to save people some time when starting out.

**Comment by christianalfoni** [comment]
Cool! :-) The new webpage will have a section on testing, let me add this to that documentation!

**Comment by tnrich** [comment]
hey @christianalfoni and @garth , did anything ever get published about testing full signals. I would like to do so in my app and but am wondering if there has been any further advancement of garth's methods. I also would like to have more info about what is happening in the `Fixture` function above. Do you think you could point me to that code @garth ? Thanks!

**Comment by garth** [comment]
@tnrich My fixture function is simply loading some test data into the database and resetting it before each system level test. Not recommended for unit tests, but fast enough for high level testing.

The contents of that very much depned on your backend, in my case I'm using postgres with the `sql-fixtures` lib.

```js
import SqlFixtures from 'sql-fixtures';
import dbConfig from '../../../database.json';

const config = {
  client: 'pg',
  connection: dbConfig.test
};

const fixtures = {
  user: require('./user'),
  xxx: require('./otherTable'),
  ...
};

export default class Fixture {

  constructor() {
    this.sqlFixtures = new SqlFixtures(config);
    this.data = null;
  }

  reset() {
    const self = this;
    return new Promise(function (resolve, reject) {
      let clearData = Object.keys(fixtures).reverse().map(table => `delete from "${table}"`).join(';\n');
      self.sqlFixtures.knex.raw(clearData).then(function () {
        self.sqlFixtures.create(fixtures, function (err, results) {
          self.data = results;
          if (err) { return reject(err); }
          let session = `{ "cookie": { "originalMaxAge": 2592000000, "expires": "2025-09-22T13:49:29Z", "httpOnly": true, "path": "/" }, "passport": { "user": ${results.user[0].id} } }`;
          self.sqlFixtures.knex.raw(`update session set sess='${session}'`).then(resolve, reject);
        });
      }, reject);
    });
  }

  destroy() {
    return this.sqlFixtures.destroy();
  }
}
```

If your using some other backend data store then you just need something similar to reset and then load test data into your store before each test.

Of course this is not specific to cerebral.

**Comment by tnrich** [comment]
Hey @garth thanks for the info there. I wasn't sure what was going on in the Fixtures file and thought maybe you were instantiating some Cerebral-specific state there. Looks like that isn't the case though :) 

How do you set up the cerebral state to be in the correct configuration before every signal you test? 

Right now I've monkey patched my controller to give access to the state tree and am manually calling:

```
beforeEach(function () {
        controller.tree.set(['sequenceData', 'circular'], true);
})
```

Thanks again for the info!

**Comment by garth** [comment]
Monkey patching sounds about right. Something official would be better.

**Comment by tnrich** [comment]
Okay, here's an update to condense my thoughts and show what I've been working on in regards to testing signals. 

While I think testing actions is far more simple/straightforward, less resource intensive/faster, and overall beneficial, I think testing signals can be a better choice than testing actions in certain cases. Individual actions can become "too modular" such that the intent of the signal can be "lost". Being able to test the entire signal allows for high modularity of actions, but still guarantees correctness of the desired behavior. Also, certain signals make more sense to be tested together, such as a signal that shouldn't be able to complete while another signal is being run, or a signal that relies on the input of a previous signal, such as a dragStart, dragging, dragStop combo. I'm not sure how I would replicate and test these intertwined scenarios without invoking the signals themselves. 

The best way I've found to test signals so far is to instantiate a new controller instance for each test case, passing it the initial state:

```
it('editorDrag starts by grabbing caret at pos 1 and moves to 2', function(done) {
    var controller = require('../controller')({
        //instantiate some default val's here:
        state: {
            selectionLayer: {
                selected: false,
            },
            caretPosition: 1,
            sequenceData: {
                sequence: 'atatatatat',
                circular: true
            },
        }
    });

.... continued below
```


Then I run a signal/signals, injecting a test action onto the end of any of the ones I want to test. (I'm still not sure completely about the repercussions of seemingly asynchronous nature of cerebral. Does a "non-async" action chain fully complete running before a new signal can be called? Will dynamically appending an action onto the end of a chain cause that action to be present in previous or subsequent calls of the same signal?) Here's what that looks like: 
```
...from above
    controller.signals.editorDragStarted({nearestBP: 1, caretGrabbed: true});
    testSignal(controller.signals.editorDragged, {
        nearestBP: 2,
    }, function() {
        controller.get('selectionLayer').start.should.equal(1);
        controller.get('selectionLayer').end.should.equal(1);
        controller.get('caretPosition').should.equal(2);
        done()
    })
    controller.signals.editorDragStopped();
});

export default function testSignal (signal, data, test) {
  signal.chain.push(function () {
    signal.chain.pop();
    test();
  })
  signal(data);
}
```

One thing that could maybe make this process easier would be if cerebral signals returned a promise when invoked, (or took a callback function). I'd be interested to hear your thoughts on that @christianalfoni . 

Thanks everyone for all the work they've put into cerebral. It is pretty mind bending, but a lot of neat/powerful patterns have shown up.

**Comment by garth** [comment]
@tnrich Instead of a promise, why not use:

```js
controller.once('signalEnd', function () {
  //assert stuff
})
```

**Comment by tnrich** [comment]
I found that this was an issue because, if you're running multiple signals in a row, but only want to test third one (for instance), it doesn't know which signalEnd to fire on. Does that make sense?

**Comment by garth** [comment]
Can you call the second one after first callback?

**Comment by tnrich** [comment]
hmm that makes sense I suppose..

**Comment by garth** [comment]
You could wrap a signal call in a promise which resolves on signal end (for testing purposes) then you can chain them one after the other, just don't call them in parallel and it will work.

**Comment by tnrich** [comment]
hmm that is also a nice idea!

**Comment by tnrich** [comment]
do you instantiate a new controller instance for every signal you test?

**Comment by garth** [comment]
No, I swap out the state only.

**Comment by tnrich** [comment]
how do you do that may i ask?

**Comment by garth** [comment]
something like:

```js
function execSignal(controller, signal) {
  return new Promise(function (resolve) {
    controller.once('signalEnd', resolve);
    signal();
  });
}
```

**Comment by tnrich** [comment]
Hmm @garth , I'm not quite getting it. So inside of execSignal, you use something like model.tree.set({newStateHere}) ? Can you show the code where you're actually resetting the state? Thanks for all the examples by the way!
