### ISSUE TITLE
Debugger Improvement: show inputs/outputs

### ISSUE THREAD

**Issue by idream3** [christianalfoni/cerebral#85]
Jotting this down really quick so I don't forget.

If the debugger showed input and output args for each action with click to log on console that would be fantastic. I seem to spend a bit of time investigating Inputs. Even when there are explicit input/outputs stated, it does not give you the entire picture. Plus, when prototyping I have many actions in one file and want to avoid the time to explicitly state input/outputs until the flow has solidified more.

**Comment by idream3** [comment]
Something like this for first implementation would be great!  Click to output object in the console.

![screen shot 2015-09-02 at 3 01 29 pm](https://cloud.githubusercontent.com/assets/1082632/9622195/0222b726-5184-11e5-9d59-aecacfd431ff.png)

**Comment by idream3** [comment]
Actually, it is only the `input` that makes sense I think. You can already see the output path and to check the output you just look at the next action's input. That will reduce visual clutter as well.

**Comment by christianalfoni** [comment]
Jup, I agree, adding an input on the right side there. As you say, outputs are not only outputs, it is also paths, so it makes more sense to have them part of the "chain" :-)

**Comment by christianalfoni** [comment]
This is now in :)
