### ISSUE TITLE
Support a signal tree or namespace for organizing lots of signals.

### ISSUE THREAD

**Issue by rohitlodha** [christianalfoni/cerebral#86]
I see that current signal is just a single level string like

     controller.signal('appMounted', ...appMounted);

As the increase beyond 30, it become difficult to keep track of them. A tree or namespace will be nice and will make it 

     controller.signal('system.appMounted', ...appMounted);

Is it possible?

**Comment by christianalfoni** [comment]
This was implemented, but it was an early feature and I do not believe there is a test for it. Could you try it and let me know? This should be documented :-)

**Comment by christianalfoni** [comment]
Tested this, will bring it back in next version!
