### ISSUE TITLE
Investigate possibility of "state trigger"

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral#87]
There are situations that a state driven architecture does not handle very well, and that is when you just want something to happen in your app. 

This could be anything from running an animation, refresh an iframe, automatically scroll or whatever. The thing is that these "do once" occurrences" can not be expressed with state in a way that makes sense.

```js
// By setting to true the component handling this would trigger
// on every following change
state.set('doThis', true);

// You could change reference and equal check the property
// in your component
state.set('doThis', {});

componentDidUpdate(prevProps) {
  if (prevProps.doThis !== this.props.doThis) {
    // do it
  }
}

// You could increase with a counter or something
state.set('doThis', 0);
state.set('doThis', 1);

componentDidUpdate(prevProps) {
  if (prevProps.doThis !== this.props.doThis) {
    // do it
  }
}
```
But these solutions does not work or feels awkward. What we really want is a state value to change and after the controller emits a `change` it should revert right back. So something like:

```js
state.trigger('doThis');
```

What is nice about this approach is that it is still just state, meaning all views have access to it. It also means that the debugger will only run ONE of these when remembering state, even though it has been triggered multiple times, and after remembering it will still revert back to "false".

But there is one problem here and that is async view layers. If there is async code in the view layer you will loose the the change. But... I do not think either React or Angular are async. So if this seems like a good idea we can implement it as EXPERIMENTAL. It is also a matter of a parent updating child components without an actual state change, then it will still be `true` and it would trigger logic in component again.

It would work something like this:

```js
function triggerIframe (input, state) {
  state.trigger('refreshIframe');
}
```

```js
componentDidUpdate() {
  if (this.props.refreshIframe) {
    this.refs.iframe.reload();
  }
}
```

**Comment by christianalfoni** [comment]
Okay, I do no think this is a good idea, handling these situations should be handled with state, though you have to be a bit more creative sometimes

**Comment by TomKaltz** [comment]
Do you not want to add this type of messaging capability because it would take away from the novelty of signals?
