### ISSUE TITLE
Serializable Object Error Is Cryptic

### ISSUE THREAD

**Issue by saulshanabrook** [christianalfoni/cerebral#89]
When I call some signals I get:

```
Uncaught Error: You have to pass a serializeable object to a signal. Did you pass a mouse event maybe?
```

I am not even passing anything to the signal in question. Is it possible to get a little bit more information in this error? I am confused on what to do.

The debugger is not registering the signal after this error happens.

**Comment by saulshanabrook** [comment]
This is similar to #48, but im not passing any sort of event. I will try to debug

**Comment by saulshanabrook** [comment]
Inside one of my actions, that the signal called I set a path to a  [momentjs](http://momentjs.com/) object. Once I changed that to set it to a serialized version it worked.

Do you think it is possible to get any more detail from that error? If not, at least it might make sense to mention this as one of the causes in the message.

**Comment by christianalfoni** [comment]
Jup, let me check here :-)

**Comment by christianalfoni** [comment]
Will be part of next release

**Comment by saulshanabrook** [comment]
Awesome! Thanks so much
