### ISSUE TITLE
Cerebral Debugger suggestion

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral#91]
- Increase indentation

**Comment by jeroenverfallie** [comment]
- Collapse the output paths in async actions that are not entered. (ie. the `error` output in your video)
- Increase the visibility of the action names vs the inputs. (the light gray background doesn't help on many screens)
- The slider sometimes feels a bit unfriendly, too precise handle, perhaps look into other sliders.

**Comment by christianalfoni** [comment]
Great input, thanks!

**Comment by christianalfoni** [comment]
Okay, I have released version 0.10 that has collapsing paths, increased size of actions. Also fixed a bug where output to a specific path was displayed on all paths
