### ISSUE TITLE
Send as param the signal triggering the event signalStart/signalEnd

### ISSUE THREAD

**Issue by jolafrite** [christianalfoni/cerebral#93]
I would like to start cerebral-router routing after my initApp signal ends.
To do that there is events we can hook into like controller.on('signalEnd') and it's great.

So I would do

```javascript
controller.on('signalEnd', () => { 
    if(this.signal.name === "appInit") {
        Router.start();
    }
});
```

But right now the name of the signal is empty so maybe one first fix would to set the name on signal construction
```javascript
controller.signal('appInit', ...loadUser);
EventEmitter.signals.appInit.name === "appInit"
```

The second fix would be to return as param the signal triggering the event :

```javascript
controller.on('signalEnd', (signal) => { 
    if(signal.name === "appInit") { // Yes the name is actually set correctly at this point, I tried
        Router.start();
    }
});
```

Maybe can also return the action and signal on actionStart/actionEnd

**Comment by saulshanabrook** [comment]
Do you mean add as a param for an action? What is the use case for this?

**Comment by saulshanabrook** [comment]
Reference: https://gitter.im/christianalfoni/cerebral?at=55ed609f97535f4058efa364

**Comment by saulshanabrook** [comment]
@jolafrite Is this still needed after [another way to get redirects working](https://gitter.im/christianalfoni/cerebral?at=55ed692b941cb60657c791d8) has been added to cerebral-router?

**Comment by christianalfoni** [comment]
@jolafrite is referring to passing the signal on `signalStart` and `signalEnd` events :-) To check what signal triggered the event.

**Comment by saulshanabrook** [comment]
@christianalfoni Yeah saw the discussion after the posting the overly pointed question, so I deleted it.

**Comment by jolafrite** [comment]
Just updated the ticket, wrote in rush
Must be more understandable now

**Comment by christianalfoni** [comment]
https://github.com/christianalfoni/cerebral/issues/99
