### ISSUE TITLE
Naming actions

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral#95]
It should be possible to dynamically name actions, typically used with factories:

```js
export default function (url) {
  function get () {

  }
  get.displayName = 'get (' + url + ')';

  return get;
};
```

Displayname will be used in debugger

**Comment by Guria** [comment]
[:+1:](https://gitter.im/christianalfoni/cerebral?at=55ede87dfd02f8cd4d2f8ed7)

**Comment by christianalfoni** [comment]
https://github.com/christianalfoni/cerebral/issues/99
