### ISSUE TITLE
by @facebook?

### ISSUE THREAD

**Issue by danmartinez101** [christianalfoni/cerebral#96]
> cerebral-react by @facebook

This sounds like Facebook created this library for cerebral. Is this the case? or are you referring to react being "by facebook"? 

I went looking information on it on Facebook's open source site but didn't find anything, so I was confused.

**Comment by christianalfoni** [comment]
Ah, @danmartinez101, I can see the confusion. I meant referring to React by Facebook. Let me fix that!

**Comment by christianalfoni** [comment]
It is fixed now, sorry about the confusion!
